-- WP6 — APN Commission Integrity on the legacy surface
-- ------------------------------------------------------------------------------
-- Closes three flagged engine gaps with idempotent, additive changes only:
--
--   1. engine.district-client  — the client-side `apn_commissions` rows of kind
--      = 'district' generated by AllbeeApp.jsx `apnBuildCommissions` DOUBLE-COUNT
--      district-head income: the engine already pays heads server-side on every
--      revenue collection (wp3 `apn_revenue_collections` trigger, idempotency
--      key `col:<id>:district`). The frontend change (separate commit) stops
--      creating those rows; no SQL change is needed here beyond the marker.
--
--   2. engine.finance-reversal — the legacy commission surface (JSON-blob
--      `apn_commissions`) has no reversal path. This patch adds an audited,
--      role-gated `apn_commission_reverse_legacy` SECURITY DEFINER RPC that
--      marks a legacy commission row `Reversed` (status, actor, reason, epoch-ms
--      timestamp), refuses paid reversals without a superadmin unlock, refuses
--      double reversals, writes the rule audit trail, then recomputes the
--      partner's withdrawal wallets so reversed money can never be withdrawn.
--
--   3. Withdrawal wallet integrity — `apn_withdrawal_source_totals` counted
--      Reversed collection and legacy amounts in the lifetime / monthly / today
--      sums. Those buckets now exclude `Reversed`, so reversed money is removed
--      from every wallet surface, not just the four workflow status buckets.
--
-- Re-runnable: all objects are `create or replace`, markers are upserts.
-- ------------------------------------------------------------------------------

-- ───────────────────────────────────────────────────────────────────────────────
-- 1. REVERSE A LEGACY COMMISSION ENTRY (admin / accountant; superadmin unlock
--    for already-paid amounts)
-- ───────────────────────────────────────────────────────────────────────────────
create or replace function public.apn_commission_reverse_legacy(
  p_commission_id text,
  p_reason text,
  p_unlock_paid boolean default false
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_row public.apn_commissions%rowtype;
  v_partner_id text;
  v_now_ms bigint;
begin
  if p_reason is null or trim(p_reason) = '' then
    raise exception 'A reversal reason is required.' using errcode = 'check_violation';
  end if;
  if not (public.is_admin() or public.can_finance() or public.is_superadmin()) then
    raise exception 'Only administrators and finance roles can reverse commissions.' using errcode = 'insufficient_privilege';
  end if;

  select * into v_row from public.apn_commissions where id = p_commission_id;
  if not found then
    raise exception 'Commission record not found.' using errcode = 'no_data_found';
  end if;
  if coalesce(v_row.data->>'status', '') = 'Reversed' then
    raise exception 'Commission is already reversed.' using errcode = 'check_violation';
  end if;
  if coalesce(v_row.data->>'status', '') = 'Paid' and not coalesce(p_unlock_paid, false) then
    raise exception 'Paid commissions require a superadmin unlock to reverse.' using errcode = 'check_violation';
  end if;
  if coalesce(p_unlock_paid, false) and not public.is_superadmin() then
    raise exception 'Only a super admin can unlock a paid reversal.' using errcode = 'insufficient_privilege';
  end if;

  v_partner_id := v_row.data->>'partnerId';
  v_now_ms := (extract(epoch from now()) * 1000)::bigint;

  update public.apn_commissions
  set data = v_row.data
        || jsonb_build_object(
             'status',              'Reversed',
             'reversedAt',          v_now_ms,
             'reversedBy',          coalesce(auth.uid()::text, 'system'),
             'reversalReason',      trim(p_reason),
             'unlockPaid',          coalesce(p_unlock_paid, false),
             'reversedCount',       coalesce((v_row.data->>'reversedCount')::int, 0) + 1
           ),
      updated_at = now()
  where id = p_commission_id;

  perform public.apn_rule_audit('reversed legacy commission', 'apn_commissions', p_commission_id,
    jsonb_build_object(
      'partnerId',     v_partner_id,
      'statusBefore',  v_row.data->>'status',
      'amount',        v_row.data->>'amount',
      'reason',        trim(p_reason),
      'unlockPaid',    coalesce(p_unlock_paid, false)
    ));

  -- The withdrawal wallets derive from apn_withdrawal_source_totals; a reversal
  -- must shrink withdrawable immediately so reversed money cannot be claimed.
  if v_partner_id is not null then
    perform public.apn_withdrawal_refresh_wallet(v_partner_id);
  end if;

  return v_row.data || jsonb_build_object(
    'status',         'Reversed',
    'reversedAt',     v_now_ms,
    'reversedBy',     coalesce(auth.uid()::text, 'system'),
    'reversalReason', trim(p_reason),
    'unlockPaid',     coalesce(p_unlock_paid, false)
  );
end;
$$;

revoke all on function public.apn_commission_reverse_legacy(text, text, boolean) from public, anon;
grant execute on function public.apn_commission_reverse_legacy(text, text, boolean) to authenticated;

-- ───────────────────────────────────────────────────────────────────────────────
-- 2. WALLET SOURCE TOTALS: exclude Reversed from every bucket
--    (was: only the four workflow status buckets excluded Reversed — the
--    lifetime / monthly / today sums still counted reversed money)
-- ───────────────────────────────────────────────────────────────────────────────
create or replace function public.apn_withdrawal_source_totals(p_partner_id text, p_wallet_type text)
returns table (pending numeric, approved numeric, withdrawable numeric, external_paid numeric, lifetime numeric, monthly numeric, today numeric)
language plpgsql security definer set search_path = public as $$
begin
  if p_wallet_type = 'referral' then
    return query
    select
      coalesce(sum(e.referral_amount) filter (where e.status = 'pending'), 0),
      coalesce(sum(e.referral_amount) filter (where e.status = 'approved'), 0),
      coalesce(sum(e.referral_amount) filter (where e.status = 'withdrawable'), 0),
      coalesce(sum(e.referral_amount) filter (where e.status = 'paid'), 0)
        + coalesce((select sum(w.amount) from public.apn_referral_withdrawals w where w.partner_id = p_partner_id and w.status = 'paid'), 0),
      coalesce(sum(e.referral_amount) filter (where e.status <> 'void'), 0),
      coalesce(sum(e.referral_amount) filter (where e.status <> 'void' and e.created_at >= date_trunc('month', now())), 0),
      coalesce(sum(e.referral_amount) filter (where e.status <> 'void' and e.collection_at >= current_date), 0)
    from public.apn_referral_earnings e where e.referrer_id = p_partner_id;
  elsif p_wallet_type = 'incentive' then
    return query
    select
      coalesce(sum(c.incentive) filter (where c.commission_status = 'Pending'), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status = 'Approved'), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status = 'Payable'), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status = 'Paid'), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status <> 'Reversed'), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status <> 'Reversed' and c.created_at >= date_trunc('month', now())), 0),
      coalesce(sum(c.incentive) filter (where c.commission_status <> 'Reversed' and c.received_date = current_date), 0)
    from public.apn_revenue_collections c where c.partner_id = p_partner_id;
  else
    return query
    with v4 as (
      select
        coalesce(sum(c.commission_generated) filter (where c.commission_status = 'Pending'), 0) pending,
        coalesce(sum(c.commission_generated) filter (where c.commission_status = 'Approved'), 0) approved,
        coalesce(sum(c.commission_generated) filter (where c.commission_status = 'Payable'), 0) withdrawable,
        coalesce(sum(c.commission_generated) filter (where c.commission_status = 'Paid'), 0) external_paid,
        coalesce(sum(c.commission_generated) filter (where c.commission_status <> 'Reversed'), 0) lifetime,
        coalesce(sum(c.commission_generated) filter (where c.commission_status <> 'Reversed' and c.created_at >= date_trunc('month', now())), 0) monthly,
        coalesce(sum(c.commission_generated) filter (where c.commission_status <> 'Reversed' and c.received_date = current_date), 0) today
      from public.apn_revenue_collections c where c.partner_id = p_partner_id
    ), legacy_rows as (
      select
        coalesce(data->>'status', 'Pending') as status,
        case when coalesce(data->>'amount','') ~ '^-?[0-9]+(\.[0-9]+)?$' then (data->>'amount')::numeric else 0 end as amount,
        case when coalesce(data->>'createdAt','') ~ '^[0-9]+$' then to_timestamp((data->>'createdAt')::numeric / 1000) end as created_at
      from public.apn_commissions where data->>'partnerId' = p_partner_id and coalesce(data->>'kind','partner') <> 'district'
    ), legacy as (
      select
        coalesce(sum(amount) filter (where status = 'Pending'), 0) pending,
        coalesce(sum(amount) filter (where status = 'Approved'), 0) approved,
        coalesce(sum(amount) filter (where status = 'Payable'), 0) withdrawable,
        coalesce(sum(amount) filter (where status = 'Paid'), 0) external_paid,
        coalesce(sum(amount) filter (where status <> 'Reversed'), 0) lifetime,
        coalesce(sum(amount) filter (where status <> 'Reversed' and created_at >= date_trunc('month', now())), 0) monthly,
        coalesce(sum(amount) filter (where status <> 'Reversed' and created_at::date = current_date), 0) today
      from legacy_rows
    )
    select v4.pending + legacy.pending, v4.approved + legacy.approved, v4.withdrawable + legacy.withdrawable,
      v4.external_paid + legacy.external_paid, v4.lifetime + legacy.lifetime, v4.monthly + legacy.monthly, v4.today + legacy.today
    from v4 cross join legacy;
  end if;
end;
$$;

revoke all on function public.apn_withdrawal_source_totals(text, text) from public, anon;
grant execute on function public.apn_withdrawal_source_totals(text, text) to authenticated;

-- ───────────────────────────────────────────────────────────────────────────────
-- 3. MIGRATION MARKERS
--    engine.district-client  — client-side district rows removed (frontend WP6)
--    engine.finance-reversal — legacy investment surface now has an audited
--                               reversal RPC; the ledger reversal screen remains
--                               the separate app-ui item.
-- ───────────────────────────────────────────────────────────────────────────────
update public.apn_migrations
set status = 'completed',
    notes = 'WP6: client-side kind=district apn_commissions rows removed; engine hierarchy entries are the single source.',
    resolved_at = coalesce(resolved_at, now()),
    resolved_by = coalesce(resolved_by, 'wp6')
where id = 'engine.district-client'
  and status <> 'completed';

update public.apn_migrations
set status = 'completed',
    notes = 'WP6: apn_commission_reverse_legacy ships audited reversal for the legacy commission surface.',
    resolved_at = coalesce(resolved_at, now()),
    resolved_by = coalesce(resolved_by, 'wp6')
where id = 'engine.finance-reversal'
  and status <> 'completed';