-- =============================================================================
-- ALLBEE — APN commission ↔ Share & Accounts finance reconciliation
-- File: supabase/pr-finance-apn-commission-reconcile.sql
--
-- Scope (canonical accounting model):
--   APN commission project
--        |-- apn_revenue_collections        (receipts, commission accrual)
--        |-- transactions (kind=income)     (finance receipt posting)
--        `-- transactions (kind=expense)    (COMMISSION EXPENSE — NEW)
--             * amount   = commission generated by the posted receipts
--             * split    = the income entry's own haji/alim split (30/70 etc.)
--             * apnProjectId + apnCommissionExpense=true link it to the project
--
-- The APN module remains the accrual/payable engine (collections, wallets,
-- withdrawal payouts). Share & Accounts is the recognition moment: recording
-- an APN income posts the receipt AND the matching commission expense in one
-- transaction, so balances() sees gross income minus commission exactly once.
--
-- Behaviour changes:
--   1. create_apn_income_transaction
--        * ATOMIC commission expense row (deterministic id 'apn-expense:<txn>')
--        * Duplicates are no longer a dead end:
--            - project id already posted  -> structured duplicate_object error
--              (message + detail JSON describing the existing state)
--            - same partner/name/client project exists WITHOUT finance ->
--              ATTACH mode: the finance entry posts against the existing APN
--              project (value/rate are authoritative on the APN project; a
--              mismatch raises a clear error). No second project is created.
--            - cancelled projects are excluded from attach matching so a new
--              commission can legitimately reuse a cancelled name.
--        * gates / search_path / RLS-off semantics unchanged.
--   2. upsert_apn_commission_project
--        * restores the partner+name+client duplicate check that the M2
--          hardening rebuild dropped, so both UIs share one duplicate
--          vocabulary. Everything else byte-identical to the live M2 version.
--   3. get_apn_commission_state (NEW, read-only)
--        * finance/admin lookup of project + collections + finance income +
--          finance expense + orphan finance rows, used by the existing-entry /
--          reconciliation UI. No writes.
--
-- Security: SECURITY DEFINER with hardened search_path, explicit role gates,
-- authenticated-only grants (each function explicitly revoked from public,
-- anon and authenticated before granting to authenticated only), no anon
-- access, no dynamic SQL, no RLS policy or helper changes. Finance locks and
-- audit immutability untouched.
-- Idempotent: create-or-replace + revoke/grant; safe to re-run.
-- Zero DML on existing data.
-- =============================================================================

begin;

-- ────────────────────────────────────────────────────────────────────────────
-- 1. create_apn_income_transaction — atomic APN project + collections +
--    finance income + COMMISSION EXPENSE, with attach/duplicate semantics.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.create_apn_income_transaction(
  p_transaction jsonb,
  p_project jsonb,
  p_collections jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_transaction_id text := nullif(p_transaction->>'id', '');
  v_project_id text := nullif(p_project->>'id', '');
  v_partner_id text := nullif(p_project->>'partnerId', '');
  v_project_value numeric := greatest(0, coalesce(nullif(p_project->>'projectValue', '')::numeric, 0));
  v_rate numeric := coalesce(nullif(p_project->>'commissionRate', '')::numeric, 0);
  v_existing_id text := null;
  v_attach bool := false;
  v_haji_pct numeric := greatest(0, least(100, coalesce(nullif(p_transaction->>'hajiPct', '')::numeric, 50)));
  v_alim_pct numeric := greatest(0, least(100, coalesce(nullif(p_transaction->>'alimPct', '')::numeric, 50)));
  v_max numeric := 0;
  v_received numeric := 0;
  v_earned numeric := 0;
  v_new_received numeric := 0;
  v_new_earned numeric := 0;
  v_status text;
  v_now_ms bigint := (extract(epoch from now()) * 1000)::bigint;
  v_ids text[] := array[]::text[];
  v_normalized jsonb := '[]'::jsonb;
  v_project_payload jsonb;
  v_transaction_payload jsonb;
  v_expense_payload jsonb;
  v_expense_id text := 'apn-expense:' || v_transaction_id;
  v_date text := coalesce(p_transaction->>'date', current_date::text);
  item jsonb;
  normalized_item jsonb;
  v_id text;
  v_amount numeric;
  v_incentive numeric;
  v_commission numeric;
begin
  if not public.can_finance() then
    raise exception 'Only Finance users can create APN income entries.' using errcode = 'insufficient_privilege';
  end if;
  if v_transaction_id is null or v_project_id is null or v_partner_id is null then
    raise exception 'Finance transaction, APN project, and partner ids are required.' using errcode = 'check_violation';
  end if;
  if coalesce(p_transaction->>'kind', 'income') <> 'income' then
    raise exception 'An APN commission entry must be an income transaction.' using errcode = 'check_violation';
  end if;
  if nullif(trim(p_project->>'projectName'), '') is null or nullif(trim(p_project->>'clientName'), '') is null then
    raise exception 'Partner, project name, and client name are required.' using errcode = 'check_violation';
  end if;
  if v_project_value <= 0 or v_rate < 0 or v_rate > 100 then
    raise exception 'Project value must be positive and commission rate must be between 0 and 100.' using errcode = 'check_violation';
  end if;
  if jsonb_typeof(coalesce(p_collections, '[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_collections, '[]'::jsonb)) = 0 then
    raise exception 'At least one APN collection is required.' using errcode = 'check_violation';
  end if;
  if exists (select 1 from public.transactions where id = v_transaction_id) then
    raise exception 'This finance entry already exists.' using errcode = 'duplicate_object',
      detail = jsonb_build_object('kind', 'finance', 'transactionId', v_transaction_id,
        'projectId', nullif((select data->>'apnProjectId' from public.transactions where id = v_transaction_id), ''))::text;
  end if;
  if not exists (
    select 1 from public.apn_users u
    where u.id = v_partner_id
      and coalesce(u.data->>'status', 'pending') = 'active'
  ) then
    raise exception 'APN income requires an active partner.' using errcode = 'check_violation';
  end if;

  -- Resolve the canonical APN project: exact id first, then partner+name+client
  -- (excluding cancelled projects so a cancelled name can be reused).
  select p.id into v_existing_id
  from public.apn_commission_projects p
  where (p.id = v_project_id
         or (coalesce(p.partner_id, p.data->>'partnerId') = v_partner_id
             and lower(trim(coalesce(p.project_name, p.data->>'projectName', p.data->>'project', ''))) = lower(trim(p_project->>'projectName'))
             and lower(trim(coalesce(p.client_name, p.data->>'clientName', ''))) = lower(trim(p_project->>'clientName'))
             and coalesce(p.status, p.data->>'status', '') <> 'Cancelled'))
  order by case when p.id = v_project_id then 0 else 1 end
  limit 1;

  if v_existing_id is not null then
    v_project_id := v_existing_id;
    if exists (
      select 1 from public.transactions t
      where t.data->>'apnProjectId' = v_project_id
        and t.data->>'kind' = 'income'
    ) then
      raise exception 'An APN commission already exists for this project.' using errcode = 'duplicate_object',
        detail = jsonb_build_object('kind', 'project-posted', 'projectId', v_project_id)::text;
    end if;
    v_attach := true;
    -- The APN project owns value/rate; the finance form must not diverge.
    select project_value, commission_rate into v_project_value, v_rate
    from public.apn_commission_projects where id = v_project_id;
    if abs(v_project_value - greatest(0, coalesce(nullif(p_project->>'projectValue', '')::numeric, 0))) > 0.01
       or abs(v_rate - coalesce(nullif(p_project->>'commissionRate', '')::numeric, 0)) > 0.01 then
      raise exception 'This commission project already exists with a value of % and a commission rate of %. Edit the APN project to change them.',
        to_char(v_project_value, 'FM999G999G990D00'), to_char(v_rate, 'FM999G999G990D00')
        using errcode = 'check_violation',
          detail = jsonb_build_object('kind', 'project-attach', 'projectId', v_project_id, 'projectValue', v_project_value, 'commissionRate', v_rate)::text;
    end if;
    select coalesce(sum(received_amount), 0), coalesce(sum(commission_generated), 0)
    into v_received, v_earned
    from public.apn_revenue_collections where project_id = v_project_id;
    if v_received > v_project_value then
      raise exception 'Existing collections exceed the project value.' using errcode = 'check_violation';
    end if;
  end if;

  v_max := round(v_project_value * v_rate / 100, 2);

  for item in select value from jsonb_array_elements(p_collections) loop
    v_id := nullif(item->>'id', '');
    if v_id is null or v_id = any(v_ids) then
      raise exception 'Each APN collection must have a unique id.' using errcode = 'unique_violation';
    end if;
    v_ids := array_append(v_ids, v_id);
    if exists (select 1 from public.apn_revenue_collections where id = v_id) then
      if exists (select 1 from public.apn_revenue_collections where id = v_id and project_id <> v_project_id) then
        raise exception 'Collection id is already assigned to another project.' using errcode = 'unique_violation';
      end if;
      continue;
    end if;
    v_amount := coalesce(nullif(item->>'receivedAmount', '')::numeric, 0);
    if v_amount <= 0 then
      raise exception 'Collection amounts must be greater than zero.' using errcode = 'check_violation';
    end if;
    v_incentive := coalesce(nullif(item->>'incentive', '')::numeric, 0);
    if v_incentive < 0 then
      raise exception 'Incentives cannot be negative.' using errcode = 'check_violation';
    end if;
    if v_received + v_amount > v_project_value then
      raise exception 'Collections cannot exceed the project value.' using errcode = 'check_violation';
    end if;
    v_commission := least(greatest(0, v_max - v_earned), round(v_amount * v_rate / 100, 2));
    v_normalized := v_normalized || jsonb_build_array(
      item || jsonb_build_object(
        'projectId', v_project_id,
        'partnerId', v_partner_id,
        'receivedAmount', v_amount,
        'commissionGenerated', v_commission,
        'incentive', v_incentive,
        'commissionStatus', case lower(trim(coalesce(item->>'commissionStatus', 'pending')))
          when 'approved' then 'Approved'
          when 'payable' then 'Payable'
          when 'paid' then 'Paid'
          else 'Pending'
        end,
        'createdBy', coalesce(item->>'createdBy', public.current_name()),
        'createdAt', coalesce(item->>'createdAt', v_now_ms::text),
        'receivedDate', coalesce(nullif(item->>'receivedDate', ''), current_date::text)
      )
    );
    v_received := v_received + v_amount;
    v_earned := v_earned + v_commission;
    v_new_received := v_new_received + v_amount;
    v_new_earned := v_new_earned + v_commission;
  end loop;

  v_status := case when v_received >= v_project_value then 'Completed' else 'Processing' end;
  v_project_payload := p_project || jsonb_build_object(
    'partnerId', v_partner_id,
    'projectValue', v_project_value,
    'commissionRate', v_rate,
    'maximumCommission', v_max,
    'totalReceived', round(v_received, 2),
    'remainingAmount', greatest(0, round(v_project_value - v_received, 2)),
    'remainingCommission', greatest(0, round(v_max - v_earned, 2)),
    'status', v_status,
    'createdAt', coalesce(p_project->>'createdAt', v_now_ms::text),
    'updatedAt', v_now_ms
  );

  -- Single transaction boundary: any trigger/RPC error aborts everything,
  -- including both finance rows.
  perform set_config('row_security', 'off', true);
  insert into public.apn_commission_projects (id, data, updated_at)
  values (v_project_id, v_project_payload, now())
  on conflict (id) do update set data = excluded.data, updated_at = now();
  for normalized_item in select value from jsonb_array_elements(v_normalized) loop
    insert into public.apn_revenue_collections (id, data, updated_at)
    values (normalized_item->>'id', normalized_item, now());
  end loop;

  v_transaction_payload := p_transaction || jsonb_build_object(
    'kind', 'income',
    'amount', round(v_new_received, 2),
    'apnProjectId', v_project_id,
    'apnCollectionIds', to_jsonb(v_ids),
    'apnCollectionId', case when array_length(v_ids, 1) = 1 then v_ids[1] else null end,
    'apnCommissionExpenseId', v_expense_id,
    'apnPostedToExistingProject', case when v_attach then true else null end,
    'createdAt', coalesce(p_transaction->>'createdAt', v_now_ms::text)
  );
  insert into public.transactions (id, data, updated_at)
  values (v_transaction_id, v_transaction_payload, now());

  -- Commission expense: one accounting impact per posting, split mirroring the
  -- income's own split. Deterministic id keeps retries idempotent.
  v_expense_payload := jsonb_build_object(
    'id', v_expense_id,
    'kind', 'expense',
    'client', p_project->>'clientName',
    'project', p_project->>'projectName',
    'amount', round(v_new_earned, 2),
    'date', v_date,
    'category', 'APN Commission',
    'scope', 'project',
    'hajiPct', v_haji_pct,
    'alimPct', v_alim_pct,
    'notes', format('APN partner commission for %s — %s%% of %s posted through finance (%s).',
      p_project->>'clientName', to_char(v_rate, 'FM990.0'), to_char(v_new_received, 'FM999G999G990D00'), p_project->>'projectName'),
    'source', 'apn-commission',
    'apnProjectId', v_project_id,
    'apnCommissionExpense', true,
    'apnCommissionOfIncome', v_transaction_id,
    'apnPartnerId', v_partner_id,
    'createdAt', coalesce(p_transaction->>'createdAt', v_now_ms::text)
  );
  insert into public.transactions (id, data, updated_at)
  values (v_expense_id, v_expense_payload, now());

  insert into public.apn_timeline (id, data, updated_at)
  values (
    'apn-timeline:' || v_partner_id || ':finance-commission:' || v_project_id,
    jsonb_build_object('id', 'apn-timeline:' || v_partner_id || ':finance-commission:' || v_project_id,
      'partnerId', v_partner_id, 'eventType', 'finance-commission-created',
      'title', 'APN commission income recorded',
      'description', format('%s received for %s; commission %s.', to_char(v_new_received, 'FM999G999G990D00'), p_project->>'projectName', to_char(v_new_earned, 'FM999G999G990D00')),
      'relatedId', v_project_id, 'performedBy', coalesce(public.current_name(), 'Finance'), 'createdAt', v_now_ms), now()
  ) on conflict (id) do nothing;
  insert into public.apn_notifications (id, data, updated_at)
  values (
    'apn-notification:commission-project:' || v_project_id,
    jsonb_build_object('id', 'apn-notification:commission-project:' || v_project_id,
      'title', 'Income recorded', 'body', format('%s received for %s. Commission credited: %s.', to_char(v_new_received, 'FM999G999G990D00'), p_project->>'projectName', to_char(v_new_earned, 'FM999G999G990D00')),
      'audience', 'partner:' || v_partner_id, 'partnerId', v_partner_id, 'level', 'Important', 'priority', 'Normal',
      'metadata', jsonb_build_object('projectId', v_project_id, 'transactionId', v_transaction_id),
      'senderName', coalesce(public.current_name(), 'ALLBEE'), 'senderDesignation', 'Finance', 'senderRole', 'System', 'senderAvatar', '/allbee-icon.png',
      'createdAt', v_now_ms, 'reads', '[]'::jsonb), now()
  ) on conflict (id) do nothing;
  insert into public.notifications (id, data, updated_at)
  values (
    'apn-notification:commission-project:' || v_project_id,
    jsonb_build_object('id', 'apn-notification:commission-project:' || v_project_id,
      'title', 'Income recorded', 'body', format('%s received for %s.', to_char(v_new_received, 'FM999G999G990D00'), p_project->>'projectName'),
      'audience', 'partner:' || v_partner_id, 'partnerId', v_partner_id, 'module', 'APN', 'priority', 'Normal',
      'metadata', jsonb_build_object('projectId', v_project_id, 'transactionId', v_transaction_id),
      'senderName', coalesce(public.current_name(), 'ALLBEE'), 'senderDesignation', 'Finance', 'senderRole', 'System', 'senderAvatar', '/allbee-icon.png',
      'createdAt', v_now_ms, 'reads', '[]'::jsonb), now()
  ) on conflict (id) do nothing;
  insert into public.audit (id, data, updated_at)
  values (
    'apn-audit:commission-project:' || v_project_id,
    jsonb_build_object('id', 'apn-audit:commission-project:' || v_project_id, 'ts', v_now_ms,
      'user', coalesce(public.current_name(), 'Finance'), 'userId', auth.uid()::text,
      'action', case when v_attach then 'recorded APN commission income (attached to existing project)' else 'recorded APN commission income' end,
      'module', 'Finance', 'entity', 'APN Commission Project', 'entityId', v_project_id,
      'metadata', jsonb_build_object('transactionId', v_transaction_id, 'expenseId', v_expense_id,
        'partnerId', v_partner_id, 'receivedAmount', v_new_received, 'commissionExpense', v_new_earned,
        'attachedToExistingProject', v_attach, 'hajiSplit', v_haji_pct, 'alimSplit', v_alim_pct)), now()
  ) on conflict (id) do nothing;

  return jsonb_build_object('projectId', v_project_id, 'transactionId', v_transaction_id,
    'expenseId', v_expense_id, 'collectionIds', to_jsonb(v_ids),
    'postedReceived', round(v_new_received, 2), 'commissionExpense', round(v_new_earned, 2),
    'status', v_status, 'mode', case when v_attach then 'attached' else 'created' end);
end;
$$;

revoke all on function public.create_apn_income_transaction(jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.create_apn_income_transaction(jsonb, jsonb, jsonb) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. upsert_apn_commission_project — restore the partner+name+client duplicate
--    check (dropped by the M2 hardening rebuild) so the APN and finance UIs
--    share one duplicate vocabulary. Everything else stays byte-identical to
--    the live hardened version.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.upsert_apn_commission_project(p_project jsonb, p_collections jsonb default '[]'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_project_id text := nullif(p_project->>'id','');
  v_partner_id text := nullif(p_project->>'partnerId','');
  v_project_value numeric := greatest(0, coalesce(nullif(p_project->>'projectValue','')::numeric, 0));
  v_rate numeric := coalesce(nullif(p_project->>'commissionRate','')::numeric, 0);
  v_max numeric := round(v_project_value * v_rate / 100, 2);
  v_received numeric := 0;
  v_earned numeric := 0;
  v_status text;
  item jsonb;
  v_id text;
  v_amount numeric;
  v_incentive numeric;
  v_commission numeric;
begin
  if not public.can_finance() and not public.is_admin() then raise exception 'Only finance or APN administrators may manage commission projects.' using errcode = 'insufficient_privilege'; end if;
  if v_project_id is null or v_partner_id is null or nullif(trim(p_project->>'projectName'),'') is null or nullif(trim(p_project->>'clientName'),'') is null then raise exception 'Partner, project name, client name, and project id are required.' using errcode = 'check_violation'; end if;
  if v_project_value <= 0 or v_rate < 0 or v_rate > 100 then raise exception 'Project value must be positive and commission rate must be between 0 and 100.' using errcode = 'check_violation'; end if;
  if exists (
    select 1 from public.apn_commission_projects p
    where p.id <> v_project_id
      and coalesce(p.partner_id, p.data->>'partnerId') = v_partner_id
      and lower(trim(coalesce(p.project_name, p.data->>'projectName', p.data->>'project', ''))) = lower(trim(p_project->>'projectName'))
      and lower(trim(coalesce(p.client_name, p.data->>'clientName', ''))) = lower(trim(p_project->>'clientName'))
      and coalesce(p.status, p.data->>'status', '') <> 'Cancelled'
  ) then raise exception 'This partner already has a commission project with that name and client.' using errcode = 'unique_violation'; end if;
  insert into public.apn_commission_projects (id, data, updated_at) values (v_project_id, p_project, now()) on conflict (id) do update set data = excluded.data, updated_at = now();
  select coalesce(sum(received_amount), 0), coalesce(sum(commission_generated), 0) into v_received, v_earned from public.apn_revenue_collections where project_id = v_project_id;
  if v_received > v_project_value then raise exception 'Existing collections exceed the project value.' using errcode = 'check_violation'; end if;
  if v_earned > v_max then raise exception 'Existing collections exceed the maximum commission.' using errcode = 'check_violation'; end if;
  for item in select value from jsonb_array_elements(coalesce(p_collections, '[]'::jsonb)) loop
    v_id := nullif(item->>'id','');
    if v_id is null then raise exception 'Each collection requires an id.' using errcode = 'check_violation'; end if;
    if exists (select 1 from public.apn_revenue_collections where id = v_id) then
      if exists (select 1 from public.apn_revenue_collections where id = v_id and project_id <> v_project_id) then raise exception 'Collection id is already assigned to another project.' using errcode = 'unique_violation'; end if;
      continue;
    end if;
    v_amount := coalesce(nullif(item->>'receivedAmount','')::numeric, 0);
    v_incentive := greatest(0, coalesce(nullif(item->>'incentive','')::numeric, 0));
    if v_amount <= 0 then raise exception 'Received amount must be greater than zero.' using errcode = 'check_violation'; end if;
    if v_received + v_amount > v_project_value then raise exception 'A collection cannot exceed the remaining project value.' using errcode = 'check_violation'; end if;
    v_commission := least(greatest(0, v_max - v_earned), round(v_amount * v_rate / 100, 2));
    item := item || jsonb_build_object('projectId', v_project_id, 'partnerId', v_partner_id, 'receivedAmount', v_amount, 'commissionGenerated', v_commission, 'incentive', v_incentive, 'commissionStatus', coalesce(item->>'commissionStatus','Pending'), 'createdBy', coalesce(item->>'createdBy', public.current_name()), 'createdAt', coalesce(item->>'createdAt', (extract(epoch from now()) * 1000)::bigint::text));
    insert into public.apn_revenue_collections (id, data, updated_at) values (v_id, item, now());
    v_received := v_received + v_amount;
    v_earned := v_earned + v_commission;
  end loop;
  v_status := case when p_project->>'status' = 'Cancelled' then 'Cancelled' when v_received = 0 then 'Pending' when v_received >= v_project_value then 'Completed' else 'Processing' end;
  update public.apn_commission_projects set data = p_project || jsonb_build_object('partnerId', v_partner_id, 'projectValue', v_project_value, 'commissionRate', v_rate, 'maximumCommission', v_max, 'totalReceived', round(v_received,2), 'remainingAmount', greatest(0, round(v_project_value-v_received,2)), 'remainingCommission', greatest(0, round(v_max-v_earned,2)), 'status', v_status, 'updatedAt', (extract(epoch from now()) * 1000)::bigint) where id = v_project_id;
  return jsonb_build_object('projectId', v_project_id, 'totalReceived', round(v_received,2), 'commissionEarned', round(v_earned,2), 'status', v_status);
end;
$$;

revoke all on function public.upsert_apn_commission_project(jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.upsert_apn_commission_project(jsonb, jsonb) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. get_apn_commission_state — read-only canonical state for the existing-
--    entry / reconciliation UI (finance or admin only).
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.get_apn_commission_state(
  p_partner_id text,
  p_project_name text,
  p_client_name text,
  p_project_id text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_project jsonb := null;
  v_project_row public.apn_commission_projects%rowtype;
  v_collections jsonb := '[]'::jsonb;
  v_finance_income jsonb := null;
  v_finance_expense jsonb := null;
  v_orphan jsonb := null;
begin
  if not public.can_finance() and not public.is_admin() then
    raise exception 'Only finance or administrator users may inspect commission state.' using errcode = 'insufficient_privilege';
  end if;
  if nullif(trim(p_project_id), '') is not null then
    select * into v_project_row from public.apn_commission_projects where id = p_project_id;
  else
    select * into v_project_row from public.apn_commission_projects p
    where coalesce(p.partner_id, p.data->>'partnerId') = p_partner_id
      and lower(trim(coalesce(p.project_name, p.data->>'projectName', p.data->>'project', ''))) = lower(trim(coalesce(p_project_name, '')))
      and lower(trim(coalesce(p.client_name, p.data->>'clientName', ''))) = lower(trim(coalesce(p_client_name, '')))
      and coalesce(p.status, p.data->>'status', '') <> 'Cancelled'
    order by p.updated_at desc
    limit 1;
  end if;

  if found then
    v_project := to_jsonb(v_project_row);
    select coalesce(jsonb_agg(to_jsonb(c) order by c.received_date), '[]'::jsonb)
    into v_collections
    from (select id, project_id, partner_id, received_amount, commission_generated, incentive, received_date, commission_status, remarks, created_at from public.apn_revenue_collections c where c.project_id = v_project_row.id) c;
    select to_jsonb(t) into v_finance_income
    from (select t.id, t.data from public.transactions t
          where t.data->>'apnProjectId' = v_project_row.id and t.data->>'kind' = 'income'
          order by t.updated_at desc limit 1) t;
    select to_jsonb(t) into v_finance_expense
    from (select t.id, t.data from public.transactions t
          where t.data->>'apnProjectId' = v_project_row.id
            and t.data->>'apnCommissionExpense' = 'true'
          order by t.updated_at desc limit 1) t;
  end if;

  -- Orphan finance rows: APN-tagged finance records whose APN project no longer
  -- exists (soft-deleted income, legacy mutate-era rows, pr-ux-1-era leftovers).
  select to_jsonb(t) into v_orphan
  from (select t.id, t.data from public.transactions t
        where (t.data->>'incomeSource' = 'apn' or t.data->>'apnProjectId' is not null)
          and t.data->>'kind' = 'income'
          and not exists (select 1 from public.apn_commission_projects p where p.id = t.data->>'apnProjectId')
          and lower(trim(coalesce(t.data->>'project', ''))) = lower(trim(coalesce(p_project_name, '')))
          and lower(trim(coalesce(t.data->>'client', ''))) = lower(trim(coalesce(p_client_name, '')))
        order by t.updated_at desc limit 1) t;

  return jsonb_build_object(
    'project', v_project,
    'collections', v_collections,
    'financeIncome', v_finance_income,
    'financeExpense', v_finance_expense,
    'orphanFinance', v_orphan
  );
end;
$$;

revoke all on function public.get_apn_commission_state(text, text, text, text) from public, anon, authenticated;
grant execute on function public.get_apn_commission_state(text, text, text, text) to authenticated;

select pg_notify('pgrst', 'reload schema');

commit;

-- =============================================================================
-- Verification checklist (run AFTER the batch — read-only):
--   1. create_apn_income_transaction creates project + collections + income +
--      expense atomically; expense amount = commission on posted receipts,
--      split mirrored from the income.
--   2. Re-running the same create raises duplicate_object (P0004) with a
--      detail JSON naming the existing project — never a second expense.
--   3. Creating an income for an existing (unposted) partner+name+client
--      project ATTACHES to it; no second project row.
--   4. attach with a different value/rate is rejected with a clear message.
--   5. upsert_apn_commission_project blocks duplicate partner+name+client
--      (cancelled projects excluded).
--   6. get_apn_commission_state returns project/collections/income/expense and
--      flags orphan finance rows; finance/admin only, no anon grant.
--   7. anon EXECUTE surface unchanged (39), no new anon grants — each function
--      is explicitly revoked from public AND anon before the authenticated
--      grant, so stale per-role anon grants cannot survive re-runs.
--   8. sec definers hardened: proconfig contains search_path=pg_catalog.
--   9. Reconciliation query (no rows expected today, 2026-08-09):
--        select count(*) from public.transactions t
--        where t.data->>'apnProjectId' is not null
--          and not exists (select 1 from public.apn_commission_projects p
--                          where p.id = t.data->>'apnProjectId');
--      (APN project with no finance income — legal; finance without project —
--       orphan, must be zero.)
--  10. Finance-lock triggers still evaluate the new expense row's data->>'date'.
-- =============================================================================
