import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Pool } from "jsr:@db/postgres@^0";
import webpush from "npm:web-push@3.6.7";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
const pool=new Pool(Deno.env.get("SUPABASE_DB_URL")!,1,true);
async function workerSecret(){const c=await pool.connect();try{const r=await c.queryObject<{decrypted_secret:string}>`select decrypted_secret from vault.decrypted_secrets where name='allbee_notification_push_worker_secret' limit 1`;return r.rows[0]?.decrypted_secret||"";}finally{c.release();}}
Deno.serve(async(req)=>{try{
 const workerKey=req.headers.get("x-notification-push-worker-key")||"";if(!workerKey||workerKey!==(await workerSecret()))return json({error:"Worker authentication required."},401);
 const url=Deno.env.get("SUPABASE_URL")!,key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,admin=createClient(url,key);const vapidPrivate=Deno.env.get("VAPID_PRIVATE_KEY")||"",vapidPublic=Deno.env.get("VAPID_PUBLIC_KEY")||"";
 if(!vapidPrivate||!vapidPublic)return json({error:"VAPID provider keys are not configured."},503);webpush.setVapidDetails(Deno.env.get("VAPID_SUBJECT")||"mailto:admin@allbeesolutions.com",vapidPublic,vapidPrivate);
 const {data:claims,error:ce}=await admin.rpc("notification_push_claim",{p_limit:20});if(ce)throw ce;let sent=0,failed=0,skipped=0;
 for(const item of claims||[]){let itemFailed=false;const aud=String(item.data?.audience||"all"),level=String(item.data?.level||item.data?.priority||"General");const {data:subs}=await admin.from("notification_push_subscriptions").select("id,user_id,subscription");let users:any[]=[];
  for(const s of subs||[]){let match=aud==="all";if(aud.startsWith("user:"))match=s.user_id===aud.slice(5);else if(["staff","intern","accountant","admin"].includes(aud)){const {data:p}=await admin.from("profiles").select("role,active,status").eq("id",s.user_id).maybeSingle();match=!!p?.active&&String(p.status||"").toLowerCase()==="active"&&p.role===aud;}if(!match)continue;const {data:pref}=await admin.from("notification_preferences").select("enabled,urgent_enabled,important_enabled,general_enabled").eq("user_id",s.user_id).maybeSingle();if(pref&&!pref.enabled)continue;if(pref&&level==="Urgent"&&!pref.urgent_enabled)continue;if(pref&&level==="Important"&&!pref.important_enabled)continue;if(pref&&level!=="Urgent"&&level!=="Important"&&!pref.general_enabled)continue;users.push(s);}
  for(const s of users){try{const info=await webpush.sendNotification(s.subscription,JSON.stringify({title:item.data?.title||"ALLBEE",body:item.data?.body||item.data?.message||"",tag:item.data?.group_key||item.data?.groupKey||item.notification_id,deep_link:item.data?.deep_link||null}));await admin.from("notification_delivery_audit").insert({notification_id:item.notification_id,user_id:s.user_id,channel:"push",status:"delivered",provider_message_id:info.headers?.['x-message-id']||null,attempted_at:new Date().toISOString(),delivered_at:new Date().toISOString()});sent++;}catch(e){itemFailed=true;failed++;const statusCode=(e as any)?.statusCode;if(statusCode===404||statusCode===410)await admin.from("notification_push_subscriptions").delete().eq("id",s.id);await admin.from("notification_delivery_audit").insert({notification_id:item.notification_id,user_id:s.user_id,channel:"push",status:"failed",error_message:String(e).slice(0,1000),attempted_at:new Date().toISOString()});}}
  if(!users.length)skipped++;await admin.rpc("notification_push_result",{p_id:item.id,p_status:itemFailed?"failed":"sent",p_error:itemFailed?"One or more push recipients failed.":null});
 }
 return json({ok:true,claimed:(claims||[]).length,sent,failed,skipped});
}catch(e){return json({error:e instanceof Error?e.message:"Push worker failed."},500)}});
