import * as Icons from "../icons.jsx";
const { LayoutDashboard, Sparkles, BookOpen, MessageCircle, FileText, ListTodo, UserCheck, Plane, MessageSquare, Send, UserPlus, Building2, Banknote, ExternalLink, Headset, FolderKanban, Home, ClipboardCheck, GraduationCap, Megaphone, Lightbulb, Wallet, ArrowDownToLine, CalendarClock, KeyRound, Bell, MegaphoneIcon, Paperclip, Sheet, BadgeCheck, TrendingUp, Award, Coins, Users, ShieldCheck, GaugeCircle, Trash2, ScrollText, Eye, User, SettingsIcon, Activity } = Icons;
export const NAV = [
  ["dashboard", "Dashboard", LayoutDashboard, "everyone"],["assistant", "ALLBEE AI", Sparkles, "everyone"],["ai-center", "AI Intelligence", Sparkles, "insight"],["knowledge-engine", "Pricing & Knowledge", BookOpen, "admin"],["requirement-builder", "Requirement Builder", MessageCircle, "admin"],["proposal-center", "Proposal Center", FileText, "admin"],["tasks", "Tasks", ListTodo, "work"],["attendance", "Attendance", UserCheck, "work"],["leave", "Leave", Plane, "leave"],["updates", "Daily updates", MessageSquare, "work"],["chat", "Team chat", Send, "collab"],["leads", "Leads & pipeline", UserPlus, "perm:leads"],["clients", "Clients", Building2, "perm:clients"],["quotations", "Quotations", FileText, "perm:quotations"],["invoices", "Invoices", Banknote, "perm:invoices"],["portal-posts", "Client updates", ExternalLink, "perm:portal-posts"],["support", "Support", Headset, "collab"],["projects", "Projects", FolderKanban, "perm:projects"],["inhouse", "In-house projects", Home, "perm:inhouse"],["testing", "Testing", ClipboardCheck, "perm:testing"],["courses", "Courses", GraduationCap, "perm:courses"],["class-students", "Class students", GraduationCap, "admin"],["marketing", "Marketing", Megaphone, "perm:marketing"],["concepts", "Concepts", Lightbulb, "perm:concepts"],["accounts", "Share & accounts", Wallet, "finance"],["withdrawals", "Withdrawals", ArrowDownToLine, "finance"],["planned", "Planned expenses", CalendarClock, "finance"],["vault", "Passwords", KeyRound, "vault"],["notifications", "Notifications", Bell, "everyone"],["announcements", "Announcements", MegaphoneIcon, "collab"],["documents", "Documents", Paperclip, "collab"],["knowledge", "Knowledge base", BookOpen, "collab"],["prompts", "Prompts", Sparkles, "perm:prompts"],["sheets", "Sheets", Sheet, "perm:sheets"],["terms", "Terms & conditions", BadgeCheck, "everyone"],["performance", "Performance", TrendingUp, "insight"],["rewards", "Rewards", Award, "collab"],["earnings", "My earnings", Coins, "everyone"],["team", "Team", Users, "admin"],["team-leads", "Team leads", ShieldCheck, "super"],["apn", "APN network", GaugeCircle, "admin"],["myteam", "My team", Users, "everyone"],["staff-salary", "Staff salary", Banknote, "admin"],["progress", "Progress", Activity, "work"],["recently-deleted", "Recently deleted", Trash2, "admin"],["audit", "Audit log", ScrollText, "admin"],["activity", "Activity", Eye, "admin"],["profile", "My profile", User, "everyone"],["settings", "Settings", SettingsIcon, "admin"]
];
export const NAV_CATEGORIES = [["overview","Overview"],["work","Work"],["sales","Sales & delivery"],["finance","Finance"],["content","Content & team"],["admin","Admin"],["personal","Personal"]];
export const NAV_CATEGORY = { dashboard:"overview",notifications:"overview",myteam:"overview",assistant:"overview","ai-center":"overview",tasks:"work",attendance:"work",leave:"work",updates:"work",progress:"work",chat:"work",leads:"sales",clients:"sales",quotations:"sales",invoices:"sales","portal-posts":"sales",support:"sales",projects:"sales",inhouse:"sales",courses:"sales","class-students":"sales",marketing:"sales",concepts:"sales",testing:"sales",accounts:"finance",withdrawals:"finance",planned:"finance",earnings:"finance","staff-salary":"finance",announcements:"content",documents:"content",knowledge:"content",prompts:"content",sheets:"content",rewards:"content",performance:"content",team:"admin","team-leads":"admin",apn:"admin","knowledge-engine":"admin","requirement-builder":"admin","proposal-center":"admin",vault:"admin","recently-deleted":"admin",audit:"admin",activity:"admin",settings:"admin",profile:"personal",terms:"personal" };
export const navCategoryOf = (key) => NAV_CATEGORY[key] || "personal";
export const NAV_SORT_LABEL = { category: "Grouped", az: "A–Z", custom: "Custom" };
export function parseHash(hash) {
  const h = (hash || "").replace(/^#\/?/, "").trim();
  if (!h) return { route:"dashboard", account:null, task:null };
  const parts = h.split("/");
  if (/^admin(?:[.;]+)?$/i.test(parts[0])) return { route:"apn", account:null, task:null, legacyAdmin:true };
  if (parts[0] === "accounts" && parts[1]) { const k=parts[1].toLowerCase(); return { route:"accounts", account:k === "haji" ? "Haji" : k === "alim" ? "Alim" : null, task:null }; }
  if (parts[0] === "tasks" && parts[1]) return { route:"tasks", account:null, task:decodeURIComponent(parts[1]) };
  if (parts[0] === "recently-deleted") return { route:"recently-deleted", account:null, task:null };
  return { route:parts[0], account:null, task:null };
}
