import MessageReactions from "./ui/MessageReactions.jsx";
import React,{useCallback,useEffect,useState} from "react";

export default function AdminClientChat({me,runtime}){
 const {supabase,Avatar,fmtDateTime,Send,MessageCircle,RefreshCw}=runtime;
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 const load=useCallback(async()=>{const {data,error}=await supabase.rpc("client_list_support_conversations");if(error)setErr(error.message);else setRows(Array.isArray(data)?data:[])},[supabase]);
 const loadMessages=useCallback(async(id)=>{const {data,error}=await supabase.rpc("apn_list_messages",{p_conversation_id:id});if(error)setErr(error.message);else setMessages(Array.isArray(data)?data:[])},[supabase]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const ch=supabase.channel("admin-client-chat").on("postgres_changes",{event:"INSERT",schema:"public",table:"apn_chat_messages"},()=>{load();if(selected)loadMessages(selected.conversation_id)}).subscribe();return()=>supabase.removeChannel(ch)},[supabase,load,loadMessages,selected]);
 const open=async r=>{setSelected(r);setErr("");await loadMessages(r.conversation_id)};
 const send=async()=>{const body=text.trim();if(!body||!selected||busy)return;setBusy(true);setText("");const {error}=await supabase.rpc("apn_send_message_v3",{p_conversation_id:selected.conversation_id,p_body:body,p_reply_to_id:null,p_mentions:[]});if(error){setErr(error.message);setText(body)}else await loadMessages(selected.conversation_id);setBusy(false)};
 if(!selected)return <div className="content"><div className="page-head"><h3>Client chat</h3><span className="spacer"/><button className="btn sm" onClick={load}><RefreshCw size={14}/>Refresh</button></div>{err&&<div className="auth-msg err">{err}</div>}<div className="card client-admin-chat-list">{rows.length===0?<div className="empty-state"><MessageCircle size={28}/><b>No client conversations yet</b><span>Client conversations will appear here after a client starts a chat with you.</span></div>:rows.map(r=><button key={r.conversation_id} onClick={()=>open(r)}><Avatar name={r.client_name} url={r.client_photo_url} size={42}/><div><b>{r.client_name}</b><span>{r.last_message||"New conversation"}</span></div><aside>{r.unread_count>0&&<i>{r.unread_count}</i>}<small>{r.last_at?fmtDateTime(r.last_at):""}</small></aside></button>)}</div></div>;
 return <div className="content"><div className="page-head"><button className="btn sm" onClick={()=>setSelected(null)}>← Clients</button><Avatar name={selected.client_name} url={selected.client_photo_url} size={34}/><h3>{selected.client_name}</h3></div>{err&&<div className="auth-msg err">{err}</div>}<div className="card client-admin-thread">{messages.map(m=><MessageReactions key={m.id} message={m} supabase={supabase} mine={String(m.sender_id)===String(me.id)} onChanged={()=>loadMessages(selected.conversation_id)}><div className={String(m.sender_id)===String(me.id)?"mine":"theirs"}><div className={m.body==="This message was deleted"?"deleted":""}><b>{String(m.sender_id)===String(me.id)?"You":m.sender_name}</b><p>{m.body}</p><small>{fmtDateTime(m.created_at)}</small></div></div></MessageReactions>)}</div><div className="composer"><textarea className="textarea" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={"Message "+selected.client_name+"…"}/><button className="btn primary" onClick={send} disabled={busy||!text.trim()}><Send size={16}/>Send</button></div></div>;
}
