import React,{useCallback,useEffect,useRef,useState} from "react";
import MessageReactions from "./ui/MessageReactions.jsx";
import ChatProfileCard from "./ui/ChatProfileCard.jsx";

export default function AdminClientChat({me,runtime}){
 const {supabase,Avatar,fmtDateTime,Send,MessageCircle,RefreshCw,ArrowLeft,MessageSquare,X}=runtime;
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[err,setErr]=useState(""),[profile,setProfile]=useState(null),[query,setQuery]=useState("");
 const scrollRef=useRef(null);
 const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);setErr("");try{const {data,error}=await supabase.rpc("client_list_support_conversations");if(error)throw error;setRows(Array.isArray(data)?data:[])}catch(error){console.error("Client chat directory failed",error);setErr(error?.hint||error?.message||"Could not load client conversations. Please retry.")}finally{if(!quiet)setLoading(false)}},[supabase]);
 const loadMessages=useCallback(async id=>{const {data,error}=await supabase.rpc("apn_list_messages",{p_conversation_id:id});if(error){setErr(error.message);return}const list=Array.isArray(data)?data:[];setMessages(list);if(list.length)await supabase.rpc("apn_mark_read",{p_conversation_id:id,p_message_id:list[list.length-1].id}).catch(()=>{});requestAnimationFrame(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight})},[supabase]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const refresh=()=>{load(true);if(selected)loadMessages(selected.conversation_id)};const ch=supabase.channel("admin-client-chat").on("postgres_changes",{event:"*",schema:"public",table:"apn_chat_messages"},refresh).on("postgres_changes",{event:"*",schema:"public",table:"apn_chat_reactions"},refresh).subscribe();return()=>supabase.removeChannel(ch)},[supabase,load,loadMessages,selected]);
 const open=async row=>{setSelected(row);setErr("");await loadMessages(row.conversation_id)};
 const send=async()=>{const body=text.trim();if(!body||!selected||busy)return;setBusy(true);setText("");const {error}=await supabase.rpc("apn_send_message_v3",{p_conversation_id:selected.conversation_id,p_body:body,p_reply_to_id:null,p_mentions:[]});if(error){setErr(error.message);setText(body)}else await loadMessages(selected.conversation_id);setBusy(false)};
 const visible=rows.filter(r=>String(r.client_name||"").toLowerCase().includes(query.trim().toLowerCase()));
 return <div className="content admin-client-chat-page"><div className="page-head"><h3>Client chat</h3><span className="spacer"/><button className="btn sm" onClick={()=>load()}><RefreshCw size={14}/>Refresh</button></div>{err&&<div className="auth-msg err client-chat-error">{err}<button className="btn sm" onClick={()=>load()}>Try again</button></div>}<div className={`card apn-admin-chat-shell client-chat-shell${selected?" has-selection":""}`}>
  <aside className="client-chat-sidebar"><div className="client-chat-sidebar-title">Client chats</div><input className="input client-chat-search" placeholder="Search client chats…" value={query} onChange={e=>setQuery(e.target.value)}/>{loading?<div className="client-chat-state"><RefreshCw size={20} className="spin"/>Loading client chats…</div>:visible.length===0?<div className="client-chat-state"><MessageCircle size={24}/><b>{rows.length?"No matching clients":"No client conversations yet"}</b><span>{rows.length?"Try another client name.":"Client conversations appear here after a client starts a chat."}</span></div>:<div className="client-chat-list">{visible.map(r=><button key={r.conversation_id} className={`apn-tc-recent-row${selected?.conversation_id===r.conversation_id?" active":""}`} onClick={()=>open(r)}><Avatar name={r.client_name} url={r.client_photo_url} size={38}/><div className="apn-tc-recent-copy"><b>{r.client_name}</b><span>{r.last_message||"No messages yet"}</span></div><div className="client-chat-row-tail">{Number(r.unread_count)>0&&<i className="apn-tc-unread">{r.unread_count}</i>}<small>{r.last_at?fmtDateTime(r.last_at):""}</small></div></button>)}</div>}</aside>
  {selected?<main className="apn-tc-chat client-chat-main"><div className="apn-tc-chathead"><button className="linkbtn client-chat-back" onClick={()=>{setSelected(null);setMessages([])}} aria-label="Back to client chats"><ArrowLeft size={17}/></button><button type="button" className="tc-profile-trigger" onClick={()=>setProfile(selected)}><Avatar name={selected.client_name} url={selected.client_photo_url} size={34}/><div><b>{selected.client_name}</b><div className="apn-tc-presence">Client conversation</div></div></button></div><div className="apn-tc-messages client-chat-messages" ref={scrollRef}>{messages.map(m=>{const mine=String(m.sender_id)===String(me.id);return <MessageReactions key={m.id} message={m} supabase={supabase} mine={mine} onChanged={()=>loadMessages(selected.conversation_id)}><div className={`apn-tc-msg ${mine?"mine":"theirs"}`}>{!mine&&<Avatar name={m.sender_name||selected.client_name} url={selected.client_photo_url} size={24}/>}<div className="apn-tc-bubble-wrap"><div className={`apn-tc-bubble${m.body==="This message was deleted"?" deleted":""}`}><div className="apn-tc-text">{m.body}</div><div className="apn-tc-time">{m.created_at?fmtDateTime(m.created_at):""}</div></div></div></div></MessageReactions>})}{!messages.length&&<div className="apn-tc-main-empty"><div><MessageSquare size={28}/><div className="apn-tc-main-title">No messages yet</div><div className="hint-line">Send the first message to {selected.client_name}.</div></div></div>}</div><div className="apn-tc-compose"><textarea className="textarea" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Message ${selected.client_name}…`} rows={2}/><button className="btn primary" onClick={send} disabled={busy||!text.trim()}><Send size={16}/>Send</button></div></main>:<div className="apn-tc-main-empty client-chat-empty"><div><MessageSquare size={30}/><div className="apn-tc-main-title">Client conversations</div><div className="hint-line">Select a client conversation to start messaging.</div></div></div>}
 </div>{profile&&<ChatProfileCard person={{...profile,name:profile.client_name,photo_url:profile.client_photo_url,role_label:"Client",bio:profile.client_bio||""}} Avatar={Avatar} X={X} onClose={()=>setProfile(null)}/>}</div>;
}
