import React,{useCallback,useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {Activity,AlertTriangle,CheckCircle2,RefreshCw,RotateCcw,Send,ShieldAlert} from "./icons.jsx";

export default function AICRMDelivery({money,fmtDateTime,emitToast}){
 const [actions,setActions]=useState([]),[health,setHealth]=useState([]),[dlq,setDlq]=useState([]),[selected,setSelected]=useState(null),[timeline,setTimeline]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const [a,h,d]=await Promise.all([supabase.rpc("ai_crm_admin_actions",{p_limit:100}),supabase.rpc("ai_crm_provider_health"),supabase.from("ai_crm_dead_letters").select("id,action_id,reason,attempts,created_at,resolved_at").is("resolved_at",null).order("created_at",{ascending:false}).limit(100)]);if(a.error)throw new Error(a.error.message);if(h.error)throw new Error(h.error.message);if(d.error)throw new Error(d.error.message);setActions(a.data||[]);setHealth(h.data||[]);setDlq(d.data||[]);}catch(e){setError(e.message||"Unable to load AI CRM delivery data.");}finally{setBusy(false);}},[]);
 useEffect(()=>{load();},[load]);
 const showTimeline=async(id)=>{setSelected(id);const {data,error:e}=await supabase.rpc("ai_crm_action_timeline",{p_action_id:id});if(e)setError(e.message);else setTimeline(data||[]);};
 const retry=async(id)=>{setBusy(true);try{const {error:e}=await supabase.rpc("ai_crm_action_retry",{p_action_id:id});if(e)throw new Error(e.message);emitToast?.("AI CRM action queued for retry.","success");await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const recover=async(id)=>{setBusy(true);try{const {error:e}=await supabase.rpc("ai_crm_dlq_recover",{p_id:id});if(e)throw new Error(e.message);emitToast?.("DLQ action recovered and queued.","success");await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const label=(s)=>String(s||"pending").replaceAll("_"," ");
 return <div className="cards-grid" style={{gridTemplateColumns:"1fr",alignItems:"start"}}>
  {error&&<div className="auth-msg err" role="alert"><AlertTriangle size={15}/>{error}</div>}
  <div className="cards-grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))"}}>
   <div className="card stat"><div className="lbl"><Send size={14}/>Actions</div><div className="num mono">{actions.length}</div></div><div className="card stat"><div className="lbl"><ShieldAlert size={14}/>Open DLQ</div><div className="num mono">{dlq.length}</div></div><div className="card stat"><div className="lbl"><Activity size={14}/>Providers</div><div className="num mono">{health.length}</div></div><div className="card stat"><div className="lbl"><CheckCircle2 size={14}/>Accepted</div><div className="num mono">{actions.filter(x=>["accepted","executed"].includes(x.delivery_state)).length}</div></div>
  </div>
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Provider health</div><div className="item-meta">Thirty-day delivery receipts aggregated by provider.</div></div><button className="btn sm" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></div>
   {health.length?health.map(h=><div className="item-row" key={h.provider}><div className="item-main"><div className="item-title">{h.provider||"Unknown"}</div><div className="item-meta">{h.success} accepted · {h.failed} failed · {h.total} total · last {h.last_event?fmtDateTime(h.last_event):"—"}</div></div><span className={`badge ${Number(h.success_rate)>=95?"pos":Number(h.success_rate)>=80?"accent":"neg"}`}>{h.success_rate}%</span></div>):<div className="hint-line">No provider receipts yet. Configure the provider and webhook, then run a delivery.</div>}
  </div>
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Retry / DLQ control</div><div className="item-meta">Automatic bounded backoff; five failed attempts move an action to the DLQ.</div></div></div>
   {dlq.length?dlq.map(d=><div className="item-row" key={d.id}><div className="item-main"><div className="item-title">{d.reason}</div><div className="item-meta">Action {String(d.action_id).slice(0,8)} · {d.attempts} attempts · {fmtDateTime(d.created_at)}</div></div><button className="btn sm primary" disabled={busy} onClick={()=>recover(d.id)}><RotateCcw size={13}/>Recover</button></div>):<div className="hint-line">No open dead letters.</div>}
   {actions.filter(x=>x.status==="failed"&&x.delivery_state!=="dead_letter").slice(0,10).map(a=><div className="item-row" key={a.id}><div className="item-main"><div className="item-title">Failed action · {label(a.action_type)}</div><div className="item-meta">{String(a.failure_reason||"Provider failure")} · {a.attempt_count} attempts</div></div><div className="row-actions"><button className="btn sm" disabled={busy} onClick={()=>retry(a.id)}><RotateCcw size={13}/>Retry</button><button className="btn sm" onClick={()=>showTimeline(a.id)}>Timeline</button></div></div>)}
  </div>
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Delivery timeline</div><div className="item-meta">Inspect every recorded provider lifecycle event for an action.</div></div></div>
   {actions.slice(0,30).map(a=><div className="item-row" key={a.id}><div className="item-main"><div className="item-title">{label(a.action_type)} <span className={`badge ${a.delivery_state==="accepted"?"pos":a.delivery_state==="dead_letter"?"neg":"pri"}`}>{label(a.delivery_state)}</span></div><div className="item-meta">{String(a.id).slice(0,8)} · {a.attempt_count} attempt(s) · {a.provider_status||"awaiting receipt"}</div></div><div className="row-actions"><button className="btn sm" onClick={()=>showTimeline(a.id)}>Timeline</button>{a.status==="failed"&&a.delivery_state!=="dead_letter"&&<button className="btn sm" disabled={busy} onClick={()=>retry(a.id)}>Retry</button>}</div></div>)}
   {!actions.length&&<div className="hint-line">No AI CRM actions have been recorded.</div>}
  </div>
  {selected&&<div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Action {String(selected).slice(0,8)} timeline</div></div></div>{timeline.length?timeline.map((e,i)=><div className="activity-timeline-item" key={`${e.created_at}-${i}`}><div className="activity-timeline-dot"/><div><div style={{fontWeight:700}}>{label(e.event_type)} · {e.provider||"internal"}</div><div className="hint-line">{label(e.status)} · {fmtDateTime(e.created_at)}{e.payload?.message_id?` · ${e.payload.message_id}`:""}</div></div></div>):<div className="hint-line">No delivery events recorded for this action.</div>}</div>}
 </div>;
}
