import React,{useCallback,useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {Activity,AlertTriangle,CheckCircle2,RefreshCw,RotateCcw,Send,ShieldAlert} from "./icons.jsx";

export default function AICRMDelivery({fmtDateTime,emitToast}){
 const [actions,setActions]=useState([]),[health,setHealth]=useState([]),[dlq,setDlq]=useState([]),[selected,setSelected]=useState(null),[timeline,setTimeline]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const [a,h,d]=await Promise.all([supabase.rpc("ai_crm_admin_actions",{p_limit:100}),supabase.rpc("ai_crm_provider_health"),supabase.from("ai_crm_dead_letters").select("id,action_id,reason,attempts,created_at,resolved_at").is("resolved_at",null).order("created_at",{ascending:false}).limit(100)]);if(a.error)throw new Error(a.error.message);if(h.error)throw new Error(h.error.message);if(d.error)throw new Error(d.error.message);setActions(Array.isArray(a.data)?a.data:[]);setHealth(Array.isArray(h.data)?h.data:[]);setDlq(d.data||[]);}catch(e){setError(e.message||"Unable to load AI CRM delivery data.");}finally{setBusy(false);}},[]);
 useEffect(()=>{load();},[load]);
 const showTimeline=async(id)=>{setSelected(id);const {data,error:e}=await supabase.rpc("ai_crm_action_timeline",{p_action_id:id});if(e)setError(e.message);else setTimeline(Array.isArray(data)?data:[]);};
 const retry=async(id)=>{setBusy(true);setError("");try{const {error:e}=await supabase.rpc("ai_crm_action_retry",{p_action_id:id});if(e)throw new Error(e.message);emitToast?.("AI CRM action requeued for retry.","success");await load();}catch(e){setError(e.message||"Retry failed.");}finally{setBusy(false);}};
 const recover=async(id)=>{setBusy(true);setError("");try{const {error:e}=await supabase.rpc("ai_crm_dlq_recover",{p_id:id});if(e)throw new Error(e.message);emitToast?.("DLQ action recovered and requeued.","success");await load();}catch(e){setError(e.message||"Recovery failed.");}finally{setBusy(false);}};
 const label=s=>String(s||"pending").replaceAll("_"," ");
 return <div className="cards-grid" style={{gridTemplateColumns:"1fr",alignItems:"start"}}>
  {error&&<div className="auth-msg err" role="alert"><AlertTriangle size={15}/>{error}</div>}
  <div className="cards-grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))"}}><div className="card stat"><div className="lbl"><Send size={14}/>Actions</div><div className="num mono">{actions.length}</div></div><div className="card stat"><div className="lbl"><ShieldAlert size={14}/>Open DLQ</div><div className="num mono">{dlq.length}</div></div><div className="card stat"><div className="lbl"><Activity size={14}/>Providers</div><div className="num mono">{health.length}</div></div><div className="card stat"><div className="lbl"><CheckCircle2 size={14}/>Delivered</div><div className="num mono">{actions.filter(x=>["accepted","delivered"].includes(x.delivery_state)).length}</div></div></div>
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Provider health</div><div className="item-meta">30-day receipts, retries, DLQ and delivery latency.</div></div><button className="btn sm" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></div>{health.length?health.map(h=><div className="item-row" key={h.provider}><div className="item-main"><div className="item-title">{h.provider||"Unknown"}</div><div className="item-meta">{h.success} delivered · {h.failed} failed · {h.retries} retries · {h.dlq} DLQ · {Number(h.latency_ms||0).toFixed(0)}ms latency · last {h.last_event?fmtDateTime(h.last_event):"—"}{h.last_failure?` · failure ${fmtDateTime(h.last_failure)}`:""}</div></div><span className={`badge ${Number(h.success_rate)>=95?"pos":Number(h.success_rate)>=80?"accent":"neg"}`}>{h.success_rate}%</span></div>):<div className="hint-line">No provider receipts yet. Configure a provider and webhook, then run a delivery.</div>}</div>
  <div className="card"><div className="item-title">Retry / DLQ controls</div><div className="item-meta" style={{marginBottom:8}}>Automatic bounded backoff; five failed attempts move an action to the DLQ. Recovery resets the attempt budget.</div>{dlq.length?dlq.map(d=><div className="item-row" key={d.id}><div className="item-main"><div className="item-title">{d.reason}</div><div className="item-meta">Action {String(d.action_id).slice(0,8)} · {d.attempts} attempts · {fmtDateTime(d.created_at)}</div></div><button className="btn sm primary" disabled={busy} onClick={()=>recover(d.id)}><RotateCcw size={13}/>Recover</button></div>):<div className="hint-line">No open dead letters.</div>}{actions.filter(x=>x.status==="failed"&&x.delivery_state!=="dead_letter").slice(0,10).map(a=><div className="item-row" key={a.id}><div className="item-main"><div className="item-title">Failed · {label(a.action_type)}</div><div className="item-meta">{a.failure_reason||"Provider failure"} · {a.attempt_count} attempts · {a.delivery_updated_at?fmtDateTime(a.delivery_updated_at):"—"}</div></div><div className="row-actions"><button className="btn sm" disabled={busy} onClick={()=>retry(a.id)}><RotateCcw size={13}/>Retry</button><button className="btn sm" onClick={()=>showTimeline(a.id)}>Timeline</button></div></div>)}</div>
  <div className="card"><div className="item-title">Delivery timeline</div><div className="item-meta" style={{marginBottom:8}}>Every attempt and provider lifecycle event, including responses and timestamps.</div>{actions.slice(0,30).map(a=><div className="item-row" key={a.id}><div className="item-main"><div className="item-title">{label(a.action_type)} <span className={`badge ${["accepted","delivered"].includes(a.delivery_state)?"pos":a.delivery_state==="dead_letter"||a.delivery_state==="failed"?"neg":"pri"}`}>{label(a.delivery_state)}</span></div><div className="item-meta">{String(a.id).slice(0,8)} · {a.attempt_count} attempt(s) · {a.provider_status||"awaiting receipt"} · {a.delivery_updated_at?fmtDateTime(a.delivery_updated_at):fmtDateTime(a.created_at)}</div></div><div className="row-actions"><button className="btn sm" onClick={()=>showTimeline(a.id)}>Timeline</button>{a.status==="failed"&&a.delivery_state!=="dead_letter"&&<button className="btn sm" disabled={busy} onClick={()=>retry(a.id)}>Retry</button>}</div></div>)}{!actions.length&&<div className="hint-line">No AI CRM actions have been recorded.</div>}</div>
  {selected&&<div className="card"><div className="item-title">Action {String(selected).slice(0,8)} timeline</div>{timeline.length?timeline.map((e,i)=><div className="activity-timeline-item" key={`${e.created_at}-${i}`}><div className="activity-timeline-dot"/><div><div style={{fontWeight:700}}>{label(e.event_type)} · {e.provider||"internal"}</div><div className="hint-line">{label(e.status)} · {fmtDateTime(e.created_at)}{e.payload?.attempt_no?` · attempt ${e.payload.attempt_no}`:""}{e.payload?.message_id?` · ${e.payload.message_id}`:""}{e.payload?.error?` · ${e.payload.error}`:""}</div>{e.payload?.response&&<pre style={{whiteSpace:"pre-wrap",fontSize:11,marginTop:4}}>{JSON.stringify(e.payload.response,null,2)}</pre>}</div></div>):<div className="hint-line">No delivery events recorded for this action.</div>}</div>}
 </div>;
}