import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {RefreshCw,TrendingUp,Wallet,Users,Lightbulb} from "./icons.jsx";
export default function AIExecutiveV5({money,fmtDate,fmtDateTime}){
 const [d,setD]=useState(null),[accuracy,setAccuracy]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);setError("");try{const [a,b]=await Promise.all([supabase.rpc("ai_intelligence_v5_dashboard"),supabase.rpc("ai_intelligence_v5_accuracy")]);if(a.error)throw new Error(a.error.message);if(b.error)throw new Error(b.error.message);setD(a.data);setAccuracy(b.data);}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{load();},[]);if(!d)return <div className="card">{error||"Loading executive intelligence…"}</div>;
 return <div className="cards-grid" style={{gridTemplateColumns:"1fr",alignItems:"start"}}>{error&&<div className="auth-msg err">{error}</div>}
  <div className="cards-grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))"}}><div className="card stat"><div className="lbl"><TrendingUp size={14}/>Predictive revenue</div><div className="num mono">{money(d.predictive_revenue)}</div></div><div className="card stat"><div className="lbl"><Wallet size={14}/>Cash forecast</div><div className="num mono">{money(d.cash_flow_forecast)}</div></div><div className="card stat"><div className="lbl">Commission forecast</div><div className="num mono">{money(d.commission_forecast)}</div></div><div className="card stat"><div className="lbl"><Users size={14}/>Win rate</div><div className="num mono">{d.win_rate}%</div></div></div>
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Executive recommendations</div><div className="item-meta">Deterministic, explainable recommendations from current CRM, partner and finance evidence.</div></div><button className="btn sm" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></div>{(d.recommendations||[]).map((r,i)=><div className="item-row" key={i}><div className="item-main"><div className="item-title"><Lightbulb size={14}/> {r.title}</div><div className="item-meta">{r.detail}</div></div><span className={`badge ${r.priority==="High"?"neg":"accent"}`}>{r.priority}</span></div>)}</div>
  <div className="card"><div className="item-title">Lead win probability</div><div className="table-wrap"><table className="tbl"><thead><tr><th>Lead</th><th>Score</th><th>Win</th><th>Lost risk</th><th>Next action</th></tr></thead><tbody>{(d.lead_predictions||[]).slice(0,15).map(x=><tr key={x.id}><td>{x.customer_name}<div className="hint-line">{x.lead_number}</div></td><td className="mono">{x.ai_lead_score}</td><td className="mono">{x.win_probability}%</td><td className="mono">{x.lost_risk}%</td><td>{x.next_action}</td></tr>)}</tbody></table></div></div>
  <div className="card"><div className="item-title">Partner performance prediction</div><div className="table-wrap"><table className="tbl"><thead><tr><th>Partner</th><th>Performance</th><th>Growth</th><th>Health</th><th>Risk</th><th>Pipeline</th></tr></thead><tbody>{(d.partner_predictions||[]).slice(0,15).map(x=><tr key={x.partner_id}><td>{x.partner_name}</td><td className="mono">{x.performance_score}</td><td className="mono">{x.growth_score}</td><td className="mono">{x.health_score}</td><td className="mono">{x.risk_score}</td><td className="mono">{money(x.pipeline_value)}</td></tr>)}</tbody></table></div></div>
  <div className="card"><div className="item-title">Forecast validation</div><div className="item-meta">Historical error measured against recorded finance periods, not a claimed accuracy guarantee.</div><div className="calc-box" style={{marginTop:12}}><div className="calc-row"><span>Measured periods</span><b className="mono">{accuracy?.periods||0}</b></div><div className="calc-row"><span>Revenue MAE</span><b className="mono">{money(accuracy?.revenue_mae||0)}</b></div><div className="calc-row"><span>Expense MAE</span><b className="mono">{money(accuracy?.expense_mae||0)}</b></div><div className="hint-line" style={{marginTop:8}}>Generated {fmtDateTime(d.generated_at)}</div></div></div>
 </div>;
}
