import React, { useState, useMemo } from "react";

export default function APNAdminReferrals({ db, isSuper, onRefresh, runtime = {} }) {
  const { supabase, todayISO, money, fmtDate, fmtDateTime, uid, round2, APN_SERVICES, SearchableSelect, apnRevenueCollectionsOf, apnPartnerStats, apnRateForPrior, apnProjectStatus, apnFinancePostedFor, apnIdFor, Coins, GaugeCircle, FileCheck2, emitToast, Confirm, Modal, Field, SelectOther, Empty, Avatar, APNAdminActivityLog, APNAdminHub, APNAdminPartners, APNAdminLeads, APNAdminCommissions, Search, Plus, Trash2, Pencil, Save, Check, X, ChevronRight, ChevronDown, ArrowRight, Download, FileText, Activity, Filter, Send, Eye, MoreVertical, Users, Wallet } = runtime;
  const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState(null);
  const settings = db.apn_referral_settings?.[0] || { enabled: true, default_percent: 1 };
  const [enabled, setEnabled] = useState(settings.enabled !== false);
  const [percent, setPercent] = useState(String(settings.default_percent ?? 1));
  const relationships = (db.apn_referral_relationships || []).slice().sort((a, b) => new Date(b.linked_at) - new Date(a.linked_at));
  const earnings = db.apn_referral_earnings || [];
  const withdrawals = db.apn_referral_withdrawals || [];
  const nameOf = (id) => (db.apn_users || []).find((row) => row.id === id)?.name || id || "—";
  const filtered = relationships.filter((row) => `${nameOf(row.referrer_id)} ${nameOf(row.referred_id)} ${row.referral_code}`.toLowerCase().includes(query.trim().toLowerCase()));
  const run = async (action, success) => { setBusy(true); setMessage(null); try { const { error } = await action(); if (error) throw error; await onRefresh?.(); setMessage({ type: "ok", text: success }); } catch (error) { setMessage({ type: "err", text: error?.message || "Referral action failed." }); } finally { setBusy(false); } };
  const updateEarning = (id, status) => run(() => supabase.rpc("apn_referral_update_earning_status", { p_earning_id: id, p_status: status, p_note: `Admin marked earning ${status}.` }), `Referral earning marked ${status}.`);
  const updateWithdrawal = (id, status) => run(() => supabase.rpc("apn_referral_set_withdrawal_status", { p_withdrawal_id: id, p_status: status, p_note: `Admin marked withdrawal ${status}.` }), `Referral withdrawal marked ${status}.`);
  const updateRelationship = (id, status) => run(() => supabase.rpc("apn_referral_set_relationship_status", { p_relationship_id: id, p_status: status }), `Referral relationship ${status}.`);
  const saveSettings = () => run(() => supabase.rpc("apn_referral_update_settings", { p_enabled: enabled, p_percent: Number(percent) }), "Referral settings saved for future collections.");
  return <div>
    {message && <div className={`auth-msg ${message.type === "ok" ? "ok" : "err"}`} style={{ marginBottom: 12 }}>{message.text}</div>}
    <div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", marginBottom: 14 }}><div className="card stat"><div className="lbl">Relationships</div><div className="num mono">{relationships.length}</div></div><div className="card stat"><div className="lbl">Lifetime earnings</div><div className="num mono">{money(earnings.reduce((s, row) => s + Number(row.referral_amount || 0), 0))}</div></div><div className="card stat"><div className="lbl">Pending earnings</div><div className="num mono">{earnings.filter((row) => row.status === "pending").length}</div></div><div className="card stat"><div className="lbl">Pending withdrawals</div><div className="num mono">{withdrawals.filter((row) => row.status === "pending").length}</div></div></div>
    {isSuper && <div className="card" style={{ marginBottom: 14 }}><div style={{ fontWeight: 700, marginBottom: 8 }}>Referral system settings</div><div className="grid2"><Field label="Default referral %" hint="Future collections only; historical snapshots never change."><input className="input mono" type="number" min="0" max="100" step="0.01" value={percent} onChange={(e) => setPercent(e.target.value)} /></Field><Field label="Status"><label className="perm-item"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />Generate future referral earnings</label></Field></div><button className="btn primary" onClick={saveSettings} disabled={busy}><Check size={14} />Save settings</button></div>}
    <div className="card" style={{ marginBottom: 14 }}><div className="toolbar" style={{ margin: 0 }}><div className="search" style={{ flex: 1 }}><Search size={16} color="var(--muted)" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search referrer, referred partner, or code…" /></div></div><div style={{ overflowX: "auto", marginTop: 10 }}><table className="tbl apn-mobile-cards"><thead><tr><th>Referrer</th><th>Referred partner</th><th>Code</th><th>Joined</th><th>Status</th><th>Earnings</th><th></th></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan="7"><Empty icon={<Users size={20} color="var(--muted)" />} title="No referral relationships" text="Direct referral relationships will appear here after a code is used." /></td></tr> : filtered.map((row) => <tr key={row.id}><td data-label="Referrer">{nameOf(row.referrer_id)}</td><td data-label="Referred">{nameOf(row.referred_id)}</td><td data-label="Code" className="mono">{row.referral_code}</td><td data-label="Joined">{fmtDate(row.linked_at)}</td><td data-label="Status"><span className={`badge ${row.status === "active" ? "pos" : "neg"}`}>{row.status}</span></td><td data-label="Earnings" className="mono">{money(earnings.filter((e) => e.relationship_id === row.id).reduce((s, e) => s + Number(e.referral_amount || 0), 0))}</td><td className="apn-card-act"><button className="btn sm" onClick={() => updateRelationship(row.id, row.status === "active" ? "disabled" : "active")} disabled={busy}>{row.status === "active" ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></div></div>
    <div className="card" style={{ marginBottom: 14 }}><div style={{ fontWeight: 700, marginBottom: 8 }}>Earnings review</div>{earnings.length === 0 ? <Empty icon={<Coins size={20} color="var(--muted)" />} title="No referral earnings" text="New collections from linked partners create snapshot-based earnings automatically." /> : earnings.slice(0, 50).map((row) => <div key={row.id} className="item-meta" style={{ justifyContent: "space-between", gap: 10, padding: "10px 0", borderBottom: "1px solid var(--border)" }}><span><b>{nameOf(row.referrer_id)}</b> · {money(row.referral_amount)} · {row.referral_percent}% snapshot · {fmtDate(row.collection_at)}</span><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span className="badge">{row.status}</span>{row.status === "pending" && <button className="btn sm" onClick={() => updateEarning(row.id, "approved")} disabled={busy}>Approve</button>}{row.status === "approved" && <button className="btn sm primary" onClick={() => updateEarning(row.id, "withdrawable")} disabled={busy}>Make withdrawable</button>}</span></div>)}</div>
    <div className="card"><div style={{ fontWeight: 700, marginBottom: 8 }}>Withdrawal review</div>{withdrawals.length === 0 ? <Empty icon={<Wallet size={20} color="var(--muted)" />} title="No referral withdrawals" text="Partner withdrawal requests will appear here." /> : withdrawals.map((row) => <div key={row.id} className="item-meta" style={{ justifyContent: "space-between", gap: 10, padding: "10px 0", borderBottom: "1px solid var(--border)" }}><span><b>{nameOf(row.partner_id)}</b> · {money(row.amount)} · {fmtDate(row.requested_at)}</span><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span className="badge">{row.status}</span>{row.status === "pending" && <><button className="btn sm" onClick={() => updateWithdrawal(row.id, "approved")} disabled={busy}>Approve</button><button className="btn sm danger" onClick={() => updateWithdrawal(row.id, "rejected")} disabled={busy}>Reject</button></>}{row.status === "approved" && <button className="btn sm primary" onClick={() => updateWithdrawal(row.id, "paid")} disabled={busy}>Mark paid</button>}</span></div>)}</div>
  </div>;
}
