import React, { useMemo, useState } from "react";

export default function APNAdminCommissions({ db, setCommStatus, openProject, onDelete, onReverse, runtime = {} }) {
  const { supabase, todayISO, money, fmtDate, fmtDateTime, uid, round2, apnRevenueCollectionsOf, apnPartnerStats, apnRateForPrior, apnProjectStatus, apnFinancePostedFor, apnIdFor, Empty, Search, Plus, Trash2, Pencil, Save, Check, X, ChevronRight, ChevronDown, ArrowRight, Download, FileText, Activity, Filter, Send, Eye, MoreVertical, emitToast, Confirm, Modal, Field } = runtime;
  const [view, setView] = useState("all");
  const projects = apnCommissionProjectsOf(db).map((project) => apnProjectSummary(db, project)).sort((a, b) => (b.updatedAt || b.createdAt || 0) - (a.updatedAt || a.createdAt || 0));
  const legacy = (db.apn_commissions || []).slice().sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
  const partnerName = (id) => (db.apn_users || []).find((u) => u.id === id)?.name || "—";
  const summary = apnCommissionDashboardSummary(db);
  const projectList = projects.filter((project) => view === "all" || view === "legacy" || project.status === view);
  const legacyList = legacy.filter((c) => view === "all" || view === "legacy" || c.status === view);
  return (
    <div>
      <div className="sumrow"><div className="card"><div className="k">Total project value</div><div className="v mono">{money(summary.totalValue)}</div></div><div className="card"><div className="k">Revenue received</div><div className="v mono pos-txt">{money(summary.totalReceived)}</div></div><div className="card"><div className="k">Outstanding revenue</div><div className="v mono">{money(summary.outstanding)}</div></div><div className="card"><div className="k">Commission paid</div><div className="v mono">{money(summary.commissionPaid)}</div></div><div className="card"><div className="k">Pending commission</div><div className="v mono">{money(summary.pendingCommission)}</div></div><div className="card"><div className="k">Processing projects</div><div className="v mono">{summary.processingProjects}</div></div><div className="card"><div className="k">Completed projects</div><div className="v mono">{summary.completedProjects}</div></div></div>
      <div className="apn-seg-scroll">{["all", "Pending", "Processing", "Completed", "Cancelled", "legacy"].map((k) => <button key={k} className={view === k ? "on" : ""} onClick={() => setView(k)}>{k === "all" ? "All" : k === "legacy" ? "Legacy entries" : k}</button>)}</div>
      <div className="card" style={{ marginBottom: 14 }}>
        <div className="apn-section-head"><h4 style={{ margin: 0 }}>Commission projects</h4><span className="hint-line">{projectList.length} project{projectList.length === 1 ? "" : "s"}</span></div>
        {projectList.length === 0 ? <Empty icon={<Coins size={22} color="var(--muted)" />} title="No commission projects" text="Create a project, then record each client payment as it arrives." />
          : <div style={{ overflowX: "auto" }}><table className="tbl apn-mobile-cards"><thead><tr><th>Partner</th><th>Project / client</th><th className="num-cell">Value</th><th className="num-cell">Received</th><th className="num-cell">Commission</th><th>Collections</th><th>Finance</th><th>Status</th><th></th></tr></thead><tbody>{projectList.map((project) => { const posted = apnFinancePostedFor(db, project.id); return <tr key={project.id}><td data-label="Partner">{partnerName(project.partnerId)}</td><td data-label="Project"><div style={{ fontWeight: 600 }}>{project.projectName}</div><div className="hint-line" style={{ fontSize: 11 }}>{project.clientName} · {project.category || "—"}</div></td><td data-label="Value" className="num-cell mono">{money(project.projectValue)}</td><td data-label="Received" className="num-cell mono">{money(project.totalReceived)}<div className="hint-line" style={{ fontSize: 11 }}>remaining {money(project.remainingAmount)}</div></td><td data-label="Commission" className="num-cell mono"><b>{money(project.commissionEarned)}</b><div className="hint-line" style={{ fontSize: 11 }}>{project.commissionRate}% · pending {money(project.remainingCommission)}</div></td><td data-label="Collections" className="mono">{project.collections.length}</td><td data-label="Finance" className="mono">{posted.expense ? <><b className="pos-txt">{money(posted.expense.amount)}</b><div className="hint-line" style={{ fontSize: 11 }}>posted · {fmtDate(posted.expense.date)}</div></> : <span className="hint-line" style={{ fontSize: 11 }}>not posted</span>}</td><td data-label="Status"><span className={"badge " + (project.status === "Completed" ? "pos" : project.status === "Cancelled" ? "neg" : project.status === "Processing" ? "accent" : "")}>{project.status}</span></td><td className="apn-card-act"><div style={{ display: "flex", gap: 6, justifyContent: "flex-end" }}><button type="button" className="btn sm" onClick={() => openProject(project)}><Pencil size={13} />Manage</button>{onDelete && <button type="button" className="iconbtn" style={{ width: 30, height: 30 }} onClick={(event) => { event.preventDefault(); event.stopPropagation(); onDelete(project); }} aria-label={`Delete commission project ${project.projectName}`} title="Delete commission project"><Trash2 size={14} /></button>}</div></td></tr>; })}</tbody></table></div>}
      </div>
      {legacyList.length > 0 && <div className="card"><div className="apn-section-head"><h4 style={{ margin: 0 }}>Legacy commission entries</h4><span className="hint-line">Existing APN commission records remain supported.</span></div><div style={{ overflowX: "auto" }}><table className="tbl apn-mobile-cards"><thead><tr><th>Partner</th><th>Project</th><th className="num-cell">Amount</th><th>Payout</th><th>Status</th></tr></thead><tbody>{legacyList.map((c) => <tr key={c.id}><td data-label="Partner">{partnerName(c.partnerId)}{c.kind === "district" && <span className="badge" style={{ marginLeft: 5 }}>District 1%</span>}</td><td data-label="Project">{c.project}<div className="hint-line" style={{ fontSize: 11 }}>{money(c.revenue)} · {c.rate}%</div></td><td data-label="Amount" className="num-cell mono" style={{ fontWeight: 700 }}>{money(c.amount)}</td><td data-label="Payout" className="mono" style={{ fontSize: 12 }}>{fmtDate(c.payoutDate)}</td><td data-label="Status" className="apn-card-act"><div className="row-actions">{c.status === APN_COMM_REVERSED ? <span className={"badge " + apnCommTone(c.status)}>{c.status}</span> : <><select className="select" style={{ width: "auto", padding: "4px 6px" }} value={c.status} onChange={(e) => setCommStatus(c, e.target.value)}>{APN_COMM_STATUS.map((s) => <option key={s}>{s}</option>)}</select><button type="button" className="btn sm" onClick={() => onReverse(c)}><Undo2 size={12} />Reverse</button></>}{c.status === APN_COMM_REVERSED && c.reversalReason && <div className="hint-line" style={{ fontSize: 11 }}>{c.reversalReason}</div>}</div></td></tr>)}</tbody></table></div></div>}
    </div>
  );
}
