import React, { useState, useEffect, useMemo } from "react";

export default function APNWithdrawalCenter({ db, pid, goProfile, reload, runtime = {} }) {
  const { Empty, money, fmtDate, fmtDateTime, apnRequestAmount, apnWithdrawalLabel, apnWalletLabel, apnWithdrawalTone, apnWithdrawalWalletFor, apnPayoutDate, apnSnapshotWallet, apnCommsOf, apnCommissionProjectsOf, apnRevenueCollectionsOf, apnProjectSummary, APN_WITHDRAWAL_TYPES, APN_COMM_REVERSED, APNMetric, supabase, emitToast, APNWithdrawalRequestModal, Wallet, Building2, ArrowDownToLine, LockIcon, BadgeCheck, Hourglass, Banknote, RefreshCw, X, CheckCircle2, Modal } = runtime;
  const [modal, setModal] = useState(null);
  const [detail, setDetail] = useState(null);
  const wallets = APN_WITHDRAWAL_TYPES.map(([type]) => apnWithdrawalWalletFor(db, pid, type));
  const requests = (db.apn_withdrawal_requests || []).filter((row) => row.partner_id === pid).slice().sort((a, b) => new Date(b.requested_at) - new Date(a.requested_at));
  const open = requests.filter((row) => ["pending", "under_review", "approved", "processing"].includes(row.status));
  const history = (db.apn_withdrawal_status_history || []).filter((row) => row.request_id === detail?.id).slice().sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
  const totalWithdrawable = wallets.reduce((sum, row) => sum + (Number(row.withdrawable) || 0), 0);
  const nextDate = wallets.find((row) => row.next_settlement_date)?.next_settlement_date;
  const cancel = async (request) => {
    try { const { error } = await supabase.rpc("apn_cancel_withdrawal", { p_request_id: request.id, p_reason: "Cancelled by partner." }); if (error) throw error; emitToast("Withdrawal cancelled and wallet unlocked.", "success"); await reload?.(); }
    catch (err) { emitToast(err?.message || "Couldn’t cancel the withdrawal.", "error"); }
  };
  return <div>
    <div className="apn-section-h" style={{ display: "flex", alignItems: "center", gap: 8 }}><Wallet size={18} /> Withdrawal Center</div>
    <div className="apn-rowcard" style={{ marginBottom: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}><div style={{ flex: 1, minWidth: 180 }}><div className="hint-line">Current withdrawable balance</div><div className="mono" style={{ fontSize: 24, fontWeight: 800 }}>{money(totalWithdrawable)}</div><div className="hint-line" style={{ marginTop: 4 }}>Next settlement: {nextDate ? fmtDate(nextDate) : "Calculated after first eligible earning"}</div></div><button className="btn" onClick={goProfile}><Building2 size={15} />Payout details</button><button className="btn primary" onClick={() => setModal({ type: "request" })}><ArrowDownToLine size={15} />Request withdrawal</button></div></div>
    <div className="apn-metrics" style={{ marginBottom: 12 }}>{wallets.map((row) => <React.Fragment key={row.wallet_type}><APNMetric k={`${apnWalletLabel(row.wallet_type)} available`} v={money(row.withdrawable)} icon={<Wallet size={13} />} tone="accent" /><APNMetric k={`${apnWalletLabel(row.wallet_type)} locked`} v={money(row.locked)} icon={<LockIcon size={13} />} /><APNMetric k={`${apnWalletLabel(row.wallet_type)} paid`} v={money(row.paid)} icon={<BadgeCheck size={13} />} tone="pos" /></React.Fragment>)}</div>
    <div className="apn-rowcard" style={{ marginBottom: 12 }}><div style={{ fontWeight: 700, marginBottom: 8 }}>Settlement summary</div><div className="apn-metrics" style={{ gridTemplateColumns: "repeat(2,minmax(0,1fr))" }}><APNMetric k="Open requests" v={open.length} icon={<Hourglass size={13} />} /><APNMetric k="Lifetime withdrawn" v={money(wallets.reduce((s, row) => s + (Number(row.paid) || 0), 0))} icon={<Banknote size={13} />} tone="pos" /><APNMetric k="Total requested" v={money(wallets.reduce((s, row) => s + (Number(row.total_requested) || 0), 0))} icon={<ArrowDownToLine size={13} />} /><APNMetric k="Processing" v={money(wallets.reduce((s, row) => s + (Number(row.total_processing) || 0), 0))} icon={<RefreshCw size={13} />} /></div></div>
    <div className="apn-rowcard" style={{ padding: 0 }}><div style={{ padding: "13px 15px", borderBottom: "1px solid var(--border)", fontWeight: 700 }}>Withdrawal history</div>{requests.length === 0 ? <div style={{ padding: 8 }}><Empty icon={<ArrowDownToLine size={22} color="var(--muted)" />} title="No withdrawal requests" text="Add payout details, then request an eligible commission, referral, or incentive balance." action={<button className="btn primary" onClick={() => setModal({ type: "request" })}><ArrowDownToLine size={14} />Request withdrawal</button>} /></div> : requests.map((row) => <div key={row.id} className="apn-rowcard" style={{ border: 0, borderBottom: "1px solid var(--border)", borderRadius: 0, boxShadow: "none", display: "flex", gap: 9, alignItems: "center" }}><button type="button" onClick={() => setDetail(row)} style={{ background: "none", border: 0, padding: 0, textAlign: "left", cursor: "pointer", flex: 1, minWidth: 0 }}><div style={{ fontWeight: 700 }}>{apnWalletLabel(row.wallet_type)} · {money(apnRequestAmount(row))}</div><div className="hint-line" style={{ fontSize: 12 }}>{fmtDateTime(row.requested_at)} · {row.preferred_method === "upi" ? "UPI" : "Bank transfer"}</div></button><span className={`badge ${apnWithdrawalTone(row.status)}`}>{apnWithdrawalLabel(row.status)}</span>{row.status === "pending" && <button className="iconbtn" style={{ width: 30, height: 30 }} title="Cancel withdrawal" aria-label="Cancel withdrawal" onClick={() => cancel(row)}><X size={14} /></button>}</div>)}</div>
    {modal?.type === "request" && <APNWithdrawalRequestModal db={db} pid={pid} onClose={() => setModal(null)} onDone={reload} />}
    {detail && <Modal title={`${apnWalletLabel(detail.wallet_type)} withdrawal`} onClose={() => setDetail(null)} footer={<button className="btn" onClick={() => setDetail(null)}>Close</button>}><div className="calc-box"><div className="calc-row"><span>Amount</span><b className="mono">{money(apnRequestAmount(detail))}</b></div><div className="calc-row"><span>Status</span><span className={`badge ${apnWithdrawalTone(detail.status)}`}>{apnWithdrawalLabel(detail.status)}</span></div><div className="calc-row"><span>Method</span><span>{detail.preferred_method === "upi" ? "UPI" : "Bank transfer"}</span></div></div><div style={{ fontWeight: 700, marginTop: 14, marginBottom: 8 }}>Status timeline</div>{history.map((item) => <div key={item.id} style={{ display: "flex", gap: 9, padding: "9px 0", borderBottom: "1px solid var(--border)" }}><CheckCircle2 size={15} color="var(--primary)" /><div><div style={{ fontWeight: 600 }}>{apnWithdrawalLabel(item.to_status)}</div><div className="hint-line" style={{ fontSize: 12 }}>{item.actor_name} · {fmtDateTime(item.created_at)}</div>{item.reason && <div className="hint-line" style={{ fontSize: 12 }}>{item.reason}</div>}</div></div>)}</Modal>}
  </div>;
}

/* ── direct referral network (separate from the commission wallet) ─────── */
const referralCodeFor = (db, pid) => (db.apn_referral_codes || []).find((row) => row.partner_id === pid) || null;
const referralWalletFor = (db, pid) => (db.apn_referral_wallets || []).find((row) => row.partner_id === pid) || { pending: 0, approved: 0, withdrawable: 0, paid: 0, lifetime: 0, monthly: 0 };
const referralLinkFor = (code) => {
  if (!code || typeof window === "undefined") return "";
  return `${window.location.origin}/apn/register?ref=${encodeURIComponent(code)}`;
};
const referralQrFor = (link) => link ? `https://quickchart.io/qr?size=220&text=${encodeURIComponent(link)}` : "";
