import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {CheckCircle2,RefreshCw,RotateCcw,ShieldAlert} from "./icons.jsx";
export default function AutomationV4({fmtDateTime,emitToast}){
 const [rules,setRules]=useState([]),[history,setHistory]=useState([]),[dlq,setDlq]=useState([]),[sim,setSim]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const [r,h,d]=await Promise.all([supabase.from("business_automation_rules").select("id,title,trigger_type,entity,condition_key,action_type,enabled,version,simulation_only").order("title"),supabase.rpc("business_automation_history",{p_limit:100}),supabase.from("business_automation_dead_letters").select("id,queue_id,reason,attempts,created_at,resolved_at").is("resolved_at",null).order("created_at",{ascending:false})]);if(r.error)throw new Error(r.error.message);if(h.error)throw new Error(h.error.message);if(d.error)throw new Error(d.error.message);setRules(r.data||[]);setHistory(h.data||[]);setDlq(d.data||[]);}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{load();},[]);
 const simulate=async(r)=>{const {data,error:e}=await supabase.rpc("business_automation_simulate",{p_rule_id:r.id,p_entity:r.entity,p_payload:{simulation:true,source:"admin"}});if(e)setError(e.message);else setSim(data);};
 const recover=async(id)=>{const {error:e}=await supabase.rpc("business_automation_dlq_recover",{p_id:id});if(e)setError(e.message);else{emitToast?.("Automation DLQ item recovered.","success");load();}};
 return <div className="cards-grid" style={{gridTemplateColumns:"1fr"}}>{error&&<div className="auth-msg err">{error}</div>}
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Automation rules & simulation</div><div className="item-meta">Every rule is versioned. Simulation never executes a side effect.</div></div><button className="btn sm" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></div>{rules.map(r=><div className="item-row" key={r.id}><div className="item-main"><div className="item-title">{r.title} <span className="badge pri">v{r.version||1}</span></div><div className="item-meta">{r.trigger_type} · {r.entity} · {r.action_type} · {r.enabled?"enabled":"disabled"}{r.simulation_only?" · simulation only":""}</div></div><button className="btn sm" onClick={()=>simulate(r)}><CheckCircle2 size={13}/>Simulate</button></div>)}</div>
  <div className="card"><div className="item-title">Execution timeline</div>{history.length?history.map(x=><div className="item-row" key={x.id}><div className="item-main"><div className="item-title">{x.rule_id} <span className={`badge ${x.status==="executed"?"pos":x.status==="dead_letter"?"neg":"accent"}`}>{x.status}</span></div><div className="item-meta">Attempt {x.attempt_no} · {fmtDateTime(x.started_at)}{x.error_message?` · ${x.error_message}`:""}</div></div></div>):<div className="hint-line">No automation executions recorded yet.</div>}</div>
  <div className="card"><div className="item-title"><ShieldAlert size={14}/> Dead-letter recovery</div>{dlq.length?dlq.map(x=><div className="item-row" key={x.id}><div className="item-main"><div className="item-title">{x.reason}</div><div className="item-meta">{x.attempts} attempts · {fmtDateTime(x.created_at)}</div></div><button className="btn sm primary" onClick={()=>recover(x.id)} disabled={busy}><RotateCcw size={13}/>Recover</button></div>):<div className="hint-line">No open automation dead letters.</div>}</div>
  {sim&&<div className="card"><div className="item-title">Simulation result</div><pre className="calc-box" style={{whiteSpace:"pre-wrap",overflowX:"auto"}}>{JSON.stringify(sim,null,2)}</pre></div>}
 </div>;
}
