import React,{useEffect,useState} from "react";
import {supabase} from "./supabaseClient";
import {CheckCircle2,RefreshCw,RotateCcw,ShieldAlert,Plus,Pencil,Trash2,X,Save} from "./icons.jsx";
export default function AutomationV4({fmtDateTime,emitToast}){
 const [rules,setRules]=useState([]),[history,setHistory]=useState([]),[dlq,setDlq]=useState([]),[sim,setSim]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[editor,setEditor]=useState(null),[saving,setSaving]=useState(false);
 const load=async()=>{setBusy(true);setError("");try{const [r,h,d]=await Promise.all([supabase.from("business_automation_rules").select("id,title,trigger_type,entity,condition_key,action_type,enabled,version,simulation_only").order("title").limit(200),supabase.rpc("business_automation_history",{p_limit:100}),supabase.from("business_automation_dead_letters").select("id,queue_id,reason,attempts,created_at,resolved_at").is("resolved_at",null).order("created_at",{ascending:false}).limit(100)]);if(r.error)throw new Error(r.error.message);if(h.error)throw new Error(h.error.message);if(d.error)throw new Error(d.error.message);setRules(r.data||[]);setHistory(h.data||[]);setDlq(d.data||[]);}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{load();},[]);

 const blankRule=()=>({id:`workflow-${Date.now()}`,title:"New workflow",trigger_type:"scheduled",entity:"crm_leads",condition_key:"stale_7d",action_type:"notify",enabled:true,version:1,simulation_only:false,config:{days:7,priority:"Important",time:"09:00",timezone:"Asia/Kolkata"}});
 const editRule=(r)=>setEditor({...r,config:{...(r.config||{})}});
 const saveRule=async()=>{if(!editor)return;setSaving(true);setError("");try{const {error:e}=await supabase.rpc("business_automation_upsert_rule",{p_id:editor.id,p_title:editor.title,p_trigger_type:editor.trigger_type,p_entity:editor.entity,p_condition_key:editor.condition_key,p_action_type:editor.action_type,p_config:editor.config||{},p_enabled:!!editor.enabled});if(e)throw new Error(e.message);setEditor(null);emitToast?.("Workflow saved and versioned.","success");await load();}catch(e){setError(e.message||"Workflow could not be saved.");}finally{setSaving(false);}};
 const deleteRule=async(id)=>{if(!window.confirm("Delete this workflow? Existing execution history is retained."))return;const {error:e}=await supabase.rpc("business_automation_delete_rule",{p_id:id});if(e)setError(e.message);else{emitToast?.("Workflow deleted.","success");load();}};
 const simulate=async(r)=>{const {data,error:e}=await supabase.rpc("business_automation_simulate",{p_rule_id:r.id,p_entity:r.entity,p_payload:{simulation:true,source:"admin"}});if(e)setError(e.message);else setSim(data);};
 const recover=async(id)=>{const {error:e}=await supabase.rpc("business_automation_dlq_recover",{p_id:id});if(e)setError(e.message);else{emitToast?.("Automation DLQ item recovered.","success");load();}};
 return <div className="cards-grid" style={{gridTemplateColumns:"1fr"}}>{error&&<div className="auth-msg err">{error}</div>}
  <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Workflow builder</div><div className="item-meta">Build Trigger → Condition → Action workflows. Every save creates a version snapshot; simulation is side-effect free.</div></div><div style={{display:"flex",gap:7}}><button className="btn sm" onClick={()=>setEditor(blankRule())}><Plus size={13}/>New workflow</button><button className="btn sm" onClick={load} disabled={busy}><RefreshCw size={13}/>Refresh</button></div></div>{rules.map(r=><div className="item-row" key={r.id}><div className="item-main"><div className="item-title">{r.title} <span className="badge pri">v{r.version||1}</span></div><div className="item-meta"><b>{r.trigger_type}</b> → <b>{r.entity}</b> → <b>{r.condition_key}</b> → <b>{r.action_type}</b> · {r.enabled?"enabled":"disabled"}{r.simulation_only?" · simulation only":""}</div></div><div style={{display:"flex",gap:5}}><button className="btn sm" onClick={()=>editRule(r)} title="Edit"><Pencil size={13}/></button><button className="btn sm" onClick={()=>simulate(r)}><CheckCircle2 size={13}/>Simulate</button><button className="btn sm" onClick={()=>deleteRule(r.id)} title="Delete"><Trash2 size={13}/></button></div></div>)}</div>
  <div className="card"><div className="item-title">Execution timeline</div>{history.length?history.map(x=><div className="item-row" key={x.id}><div className="item-main"><div className="item-title">{x.rule_id} <span className={`badge ${x.status==="executed"?"pos":x.status==="dead_letter"?"neg":"accent"}`}>{x.status}</span></div><div className="item-meta">Attempt {x.attempt_no} · {fmtDateTime(x.started_at)}{x.error_message?` · ${x.error_message}`:""}</div></div></div>):<div className="hint-line">No automation executions recorded yet.</div>}</div>
  <div className="card"><div className="item-title"><ShieldAlert size={14}/> Dead-letter recovery</div>{dlq.length?dlq.map(x=><div className="item-row" key={x.id}><div className="item-main"><div className="item-title">{x.reason}</div><div className="item-meta">{x.attempts} attempts · {fmtDateTime(x.created_at)}</div></div><button className="btn sm primary" onClick={()=>recover(x.id)} disabled={busy}><RotateCcw size={13}/>Recover</button></div>):<div className="hint-line">No open automation dead letters.</div>}</div>
  {editor&&<div className="card"><div className="item-row"><div className="item-title"><CheckCircle2 size={14}/> Workflow builder</div><button className="iconbtn" onClick={()=>setEditor(null)}><X size={15}/></button></div><div className="cards-grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))"}}><label className="field"><span>Workflow ID</span><input className="input mono" value={editor.id} onChange={e=>setEditor({...editor,id:e.target.value.replace(/\s+/g,"-").toLowerCase()})}/></label><label className="field"><span>Title</span><input className="input" value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label className="field"><span>Trigger</span><select className="input" value={editor.trigger_type} onChange={e=>setEditor({...editor,trigger_type:e.target.value})}><option value="scheduled">Scheduled</option><option value="event">Event</option></select></label><label className="field"><span>Entity</span><input className="input" value={editor.entity} onChange={e=>setEditor({...editor,entity:e.target.value})}/></label><label className="field"><span>Condition</span><input className="input" value={editor.condition_key} onChange={e=>setEditor({...editor,condition_key:e.target.value})}/></label><label className="field"><span>Action</span><select className="input" value={editor.action_type} onChange={e=>setEditor({...editor,action_type:e.target.value})}><option value="notify">Notification</option><option value="schedule_follow_up">Schedule follow-up</option><option value="send_email">Email</option><option value="send_whatsapp">WhatsApp</option></select></label><label className="field"><span>Schedule time (IST)</span><input className="input" type="time" value={editor.config?.time||"09:00"} onChange={e=>setEditor({...editor,config:{...editor.config,time:e.target.value,timezone:"Asia/Kolkata"}})}/></label><label className="field"><span>Condition days</span><input className="input" type="number" min="0" value={editor.config?.days ?? 7} onChange={e=>setEditor({...editor,config:{...editor.config,days:Number(e.target.value)}})}/></label></div><label style={{display:"flex",gap:8,alignItems:"center",margin:"10px 0"}}><input type="checkbox" checked={!!editor.enabled} onChange={e=>setEditor({...editor,enabled:e.target.checked})}/> Enabled</label><div className="item-row"><div className="hint-line">Trigger → condition → action is persisted server-side. Approval remains required for queued automation proposals.</div><button className="btn primary" onClick={saveRule} disabled={saving}><Save size={13}/>{saving?"Saving…":"Save & version"}</button></div></div>}
  {sim&&<div className="card"><div className="item-title">Simulation result</div><pre className="calc-box" style={{whiteSpace:"pre-wrap",overflowX:"auto"}}>{JSON.stringify(sim,null,2)}</pre></div>}
 </div>;
}
