import React,{useCallback,useEffect,useRef,useState} from "react";
import {ArrowLeft,ChevronRight,MessageCircle,Send} from "./icons.jsx";

const SUPPORT_ORDER=["saranya","haji","mohamed backer alim"];
const labelFor=(n="")=>/mohamed\s+backer\s+alim/i.test(n)?"Chat with AllBee Founder and CEO":/^haji$/i.test(n.trim())?"Chat with AllBee Co-founder and CFO":"Chat with AllBee Admins";
export default function ClientSupportChat({profile,runtime}){
 const {supabase,Avatar,fmtDateTime,emitToast}=runtime; const [contacts,setContacts]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState(""); const selectedRef=useRef(null); selectedRef.current=selected;
 const loadContacts=useCallback(async()=>{const {data,error}=await supabase.rpc("client_support_directory"); if(error){setErr(error.message);return;} const rows=(data||[]).filter(x=>SUPPORT_ORDER.includes(String(x.name||"").trim().toLowerCase())).sort((a,b)=>SUPPORT_ORDER.indexOf(a.name.trim().toLowerCase())-SUPPORT_ORDER.indexOf(b.name.trim().toLowerCase())); setContacts(rows);},[supabase]);
 const loadMessages=useCallback(async(conv)=>{const {data,error}=await supabase.rpc("apn_list_messages",{p_conversation_id:conv.id}); if(error){setErr(error.message);return;} setMessages(Array.isArray(data)?data:[]);},[supabase]);
 useEffect(()=>{loadContacts()},[loadContacts]);
 useEffect(()=>{const ch=supabase.channel(`client-support:${profile.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"apn_chat_messages"},()=>{if(selectedRef.current)loadMessages(selectedRef.current)}).subscribe(); return()=>supabase.removeChannel(ch)},[profile.id,supabase,loadMessages]);
 const open=async(c)=>{setBusy(true);setErr("");try{const {data,error}=await supabase.rpc("apn_get_or_create_admin_conversation",{p_admin_id:c.id});if(error)throw error;const row=data?.[0];if(!row)throw new Error("Chat unavailable.");const conv={id:row.conversation_id,subject:c.name,contact:c};setSelected(conv);await loadMessages(conv);}catch(e){setErr(e.message)}finally{setBusy(false)}};
 const send=async()=>{const body=text.trim();if(!body||!selected||busy)return;setBusy(true);setText("");try{const {error}=await supabase.rpc("apn_send_message_v3",{p_conversation_id:selected.id,p_body:body,p_reply_to_id:null,p_mentions:[]});if(error)throw error;await loadMessages(selected);}catch(e){setText(body);setErr(e.message);emitToast?.(e.message||"Could not send message.","error")}finally{setBusy(false)}};
 if(selected)return <section className="client-chat-thread card"><header><button className="iconbtn" onClick={()=>setSelected(null)} aria-label="Back to support contacts"><ArrowLeft size={18}/></button><Avatar name={selected.contact.name} url={selected.contact.photo_url} size={42}/><div><b>{selected.contact.name}</b><span>{labelFor(selected.contact.name)}</span></div></header>{err&&<div className="auth-msg err">{err}</div>}<div className="client-chat-messages">{messages.length===0&&<div className="client-chat-empty"><MessageCircle size={34}/><b>Start a conversation</b><span>Send a message to {selected.contact.name}. Your conversation stays here.</span></div>}{messages.map(m=><div key={m.id} className={`client-chat-bubble ${String(m.sender_id)===String(profile.id)?"mine":"theirs"}`}><b>{String(m.sender_id)===String(profile.id)?"You":m.sender_name}</b><p>{m.body}</p><small>{fmtDateTime(m.created_at)}</small></div>)}</div><footer><textarea className="textarea" rows={1} value={text} onChange={e=>setText(e.target.value)} placeholder={`Message ${selected.contact.name}…`} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button className="btn primary" disabled={busy||!text.trim()} onClick={send}><Send size={17}/>Send</button></footer></section>;
 return <section className="client-support-chat"><div className="client-chat-title"><span>ALLBEE SUPPORT</span><h2>Chat with our team</h2><p>Choose who you'd like to speak with. These are your dedicated ALLBEE support contacts.</p></div>{err&&<div className="auth-msg err">{err}</div>}<div className="client-support-list">{contacts.map(c=><button key={c.id} onClick={()=>open(c)} disabled={busy}><Avatar name={c.name} url={c.photo_url} size={58}/><div><b>{c.name}</b><span>{labelFor(c.name)}</span></div><i>Support</i><ChevronRight size={22}/></button>)}</div></section>;
}
