import React, { useState, useEffect, useMemo, useCallback } from "react";
import { supabase } from "./supabaseClient";
import * as Icons from "./icons.jsx";

export default function EnterpriseCRM(props) {
  const runtime = props.runtime || {};
  const { todayISO, round2, money, fmtDate, fmtDateTime, uid, emitToast, Confirm, Modal, Field, SelectOther, Empty, Avatar, PRIORITIES, ContactButtons, ...iconOverrides } = runtime;
  const { Search, Plus, Trash2, Pencil, Save, Check, X, ChevronRight, ArrowRight, Download, FileText, Activity, Filter, Send, Eye, MoreVertical, UserPlus, Flame, CalendarClock, Trophy, XCircle, Coins, GaugeCircle, FolderKanban, AlertTriangle } = { ...Icons, ...iconOverrides };
  const { db, team = [], me, isAdmin, reload } = props;
  const [tab, setTab] = useState("overview");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [priority, setPriority] = useState("All");
  const [activityQuery, setActivityQuery] = useState("");
  const [activityType, setActivityType] = useState("All");
  const [selected, setSelected] = useState(null);
  const [customerQuery, setCustomerQuery] = useState("");
  const [customerSort, setCustomerSort] = useState("risk");
  const [selectedCustomerKey, setSelectedCustomerKey] = useState(null);
  const [modal, setModal] = useState(null);
  const [dragId, setDragId] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [leadForm, setLeadForm] = useState({ customer_name: "", company: "", mobile: "", email: "", source: "Manual Entry", project_category: "Website", expected_budget: "", expected_closing_date: "", priority: "Medium", district: "", state: "Tamil Nadu", remarks: "", tags: "" });
  const [followForm, setFollowForm] = useState({ follow_up_date: todayISO(), follow_up_time: "10:00", priority: "Medium", notes: "", next_follow_up: "" });
  const [quoteForm, setQuoteForm] = useState({ title: "", service_type: "Website", description: "", quantity: "1", unit_price: "", discount: "0", gst: "18", validity_until: "" });
  const [quotePricing, setQuotePricing] = useState(null);
  const [quotePricingBusy, setQuotePricingBusy] = useState(false);
  const [revenueForm, setRevenueForm] = useState({ amount: "", received_at: todayISO(), incentive: "0", remarks: "" });
  const leads = db.crm_leads || [];
  const followUps = db.crm_follow_ups || [];
  const quotes = db.crm_quotations || [];
  const projects = db.crm_projects || [];
  const revenue = db.crm_revenue_collections || [];
  const partners = (db.apn_users || []).filter((p) => p.status === "active");
  const employees = team.filter((p) => p.role !== "client" && p.role !== "partner" && p.active !== false);
  useEffect(() => {
    let alive = true;
    setQuotePricingBusy(true);
    supabase.rpc("knowledge_get_pricing", { p_service: quoteForm.service_type }).then(({ data }) => {
      if (!alive) return;
      setQuotePricing(data || null);
      setQuotePricingBusy(false);
      if (data?.base != null) setQuoteForm((current) => current.unit_price === "" ? { ...current, unit_price: String(data.base), description: current.description || data.baseLabel || "" } : current);
    }).catch(() => { if (alive) setQuotePricingBusy(false); });
    return () => { alive = false; };
  }, [quoteForm.service_type]);
  const dashboard = useMemo(() => {
    const active = leads.filter((l) => !["Won", "Lost", "Cancelled", "Converted", "Closed"].includes(l.status));
    const won = leads.filter((l) => ["Won", "Converted", "Closed"].includes(l.status));
    const decided = leads.filter((l) => ["Won", "Converted", "Closed", "Lost"].includes(l.status));
    return { newLeads: leads.filter((l) => l.status === "New").length, hot: leads.filter((l) => ["High", "Urgent"].includes(l.priority)).length, cold: leads.filter((l) => l.priority === "Low").length, followUps: followUps.filter((f) => f.status === "Open" && f.follow_up_date >= todayISO()).length, missed: followUps.filter((f) => f.status === "Open" && f.follow_up_date < todayISO()).length, won: won.length, lost: leads.filter((l) => l.status === "Lost").length, revenue: revenue.filter((r) => r.status !== "Cancelled").reduce((s, r) => s + Number(r.received_amount || 0), 0), conversion: decided.length ? Math.round(won.length * 100 / decided.length) : 0, active: active.length };
  }, [leads, followUps, revenue]);
  const visibleLeads = useMemo(() => {
    const q = query.trim().toLowerCase();
    return leads.filter((l) => (status === "All" || l.status === status) && (priority === "All" || l.priority === priority) && (!q || [l.lead_number, l.customer_name, l.company, l.mobile, l.email, l.district, l.state, l.source, l.project_category, ...(l.tags || [])].filter(Boolean).join(" ").toLowerCase().includes(q))).sort((a, b) => new Date(b.updated_at || b.created_at || 0) - new Date(a.updated_at || a.created_at || 0));
  }, [leads, query, status, priority]);
  const call = async (name, args) => {
    setBusy(true); setError("");
    try { const { data, error: rpcError } = await supabase.rpc(name, args); if (rpcError) throw new Error(rpcError.message); await reload(); return data; }
    catch (e) { setError(e.message || "CRM action failed."); throw e; }
    finally { setBusy(false); }
  };
  const saveLead = async () => {
    if (!leadForm.customer_name.trim()) { setError("Customer name is required."); return; }
    await call("crm_create_lead", { p_payload: { ...leadForm, expected_budget: Number(leadForm.expected_budget || 0), tags: leadForm.tags.split(",").map((x) => x.trim()).filter(Boolean), lead_owner_id: me?.id } });
    setModal(null); setLeadForm({ customer_name: "", company: "", mobile: "", email: "", source: "Manual Entry", project_category: "Website", expected_budget: "", expected_closing_date: "", priority: "Medium", district: "", state: "Tamil Nadu", remarks: "", tags: "" });
  };
  const updateStatus = async (lead, next) => { await call("crm_update_lead", { p_lead_id: lead.id, p_patch: { status: next } }); };
  const assign = async (lead, employeeId, partnerId) => { await call("crm_assign_lead", { p_lead_id: lead.id, p_employee_id: employeeId || null, p_partner_id: partnerId || null, p_district_head_id: null, p_state_head_id: null }); };
  const addFollowUp = async () => { if (!selected) return; await call("crm_add_follow_up", { p_lead_id: selected.id, p_payload: followForm }); setModal(null); };
  const createQuote = async () => {
    if (!selected || !quoteForm.title.trim()) { setError("Select a lead and add a quotation title."); return; }
    await call("crm_create_quotation", { p_lead_id: selected.id, p_payload: { service_type: quoteForm.service_type, title: quoteForm.title, discount: Number(quoteForm.discount || 0), gst: Number(quoteForm.gst || 0), validity_until: quoteForm.validity_until || null, pricing_source: "knowledge_engine", items: [{ description: quoteForm.description || quoteForm.title, quantity: Number(quoteForm.quantity || 1), unit_price: Number(quoteForm.unit_price || quotePricing?.base || 0) }] } });
    setModal(null);
  };
  const recordRevenue = async () => { if (!selected?.project_id || Number(revenueForm.amount) <= 0) { setError("Select a converted lead and enter a positive collection."); return; } await call("crm_record_revenue", { p_project_id: selected.project_id, p_amount: Number(revenueForm.amount), p_received_at: revenueForm.received_at, p_incentive: Number(revenueForm.incentive || 0), p_remarks: revenueForm.remarks || null }); setModal(null); };
  const selectLead = (lead) => { setSelected(lead); setTab("leads"); };
  const activityFor = (leadId) => (db.crm_activities || []).filter((a) => a.lead_id === leadId).sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  const activityTypes = useMemo(() => ["All", ...Array.from(new Set((db.crm_activities || []).map((a) => a.event_type).filter(Boolean))).sort()], [db.crm_activities]);
  const visibleActivities = useMemo(() => {
    const q = activityQuery.trim().toLowerCase();
    return (db.crm_activities || []).filter((a) => (activityType === "All" || a.event_type === activityType) && (!q || [a.title, a.description, a.actor_name, a.event_type, a.metadata ? JSON.stringify(a.metadata) : ""].filter(Boolean).join(" ").toLowerCase().includes(q))).sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  }, [db.crm_activities, activityQuery, activityType]);
  const pipelineValue = useMemo(() => leads.filter((l) => !["Won", "Lost", "Cancelled", "Converted", "Closed"].includes(l.status)).reduce((sum, l) => sum + Number(l.expected_budget || 0), 0), [leads]);
  const quotePipelineValue = useMemo(() => quotes.filter((q) => !["Rejected", "Expired"].includes(q.status)).reduce((sum, q) => sum + Number(q.grand_total || 0), 0), [quotes]);
  const customer360 = useMemo(() => {
    const groups = new Map();
    const keyFor = (l) => {
      const email = String(l.email || "").trim().toLowerCase();
      const mobile = String(l.mobile || "").replace(/\D/g, "").slice(-10);
      const company = String(l.company || "").trim().toLowerCase();
      return email ? `email:${email}` : mobile ? `mobile:${mobile}` : company ? `company:${company}` : `lead:${l.id}`;
    };
    leads.forEach((l) => {
      const key = keyFor(l);
      if (!groups.has(key)) groups.set(key, { key, name: l.customer_name || "Unnamed customer", company: l.company || "", email: l.email || "", mobile: l.mobile || "", leads: [], activities: [], quotes: [], projects: [], revenue: 0 });
      const g = groups.get(key);
      g.leads.push(l);
      if (!g.name || g.name === "Unnamed customer") g.name = l.customer_name || g.name;
      if (!g.company) g.company = l.company || "";
      if (!g.email) g.email = l.email || "";
      if (!g.mobile) g.mobile = l.mobile || "";
    });
    groups.forEach((g) => {
      const ids = new Set(g.leads.map((l) => l.id));
      g.activities = (db.crm_activities || []).filter((a) => ids.has(a.lead_id)).sort((a,b) => new Date(b.created_at) - new Date(a.created_at));
      g.quotes = quotes.filter((q) => ids.has(q.lead_id));
      const projectIds = new Set(g.leads.map((l) => l.project_id).filter(Boolean));
      g.projects = projects.filter((p) => projectIds.has(p.id));
      g.revenue = revenue.filter((r) => projectIds.has(r.project_id) && r.status !== "Cancelled").reduce((sum, r) => sum + Number(r.received_amount || 0), 0);
      g.pipeline = g.leads.filter((l) => !["Won", "Lost", "Cancelled", "Converted", "Closed"].includes(l.status)).reduce((sum, l) => sum + Number(l.expected_budget || 0), 0);
      g.lastActivity = g.activities[0]?.created_at || null;
      g.nextFollowUp = followUps.filter((f) => ids.has(f.lead_id) && f.status === "Open" && f.follow_up_date >= todayISO()).sort((a,b) => String(a.follow_up_date).localeCompare(String(b.follow_up_date)))[0] || null;
    });
    const q = customerQuery.trim().toLowerCase();
    return Array.from(groups.values()).filter((g) => !q || [g.name, g.company, g.email, g.mobile].join(" ").toLowerCase().includes(q)).sort((a,b) => new Date(b.lastActivity || 0) - new Date(a.lastActivity || 0));
  }, [leads, quotes, projects, revenue, followUps, db.crm_activities, customerQuery, todayISO]);
  const selectedCustomer = useMemo(() => customer360.find((g) => g.key === selectedCustomerKey) || customer360[0] || null, [customer360, selectedCustomerKey]);
  const crmIntelligence = useMemo(() => {
    const now = Date.now();
    const staleDays = 7 * 86400000;
    const stale = leads.filter((l) => !["Won","Lost","Cancelled","Converted","Closed"].includes(l.status) && now - new Date(l.updated_at || l.created_at || 0).getTime() > staleDays);
    const overdue = followUps.filter((f) => f.status === "Open" && f.follow_up_date < todayISO);
    const quoteRisk = quotes.filter((q) => !["Accepted","Converted","Rejected","Expired"].includes(q.status) && q.validity_until && q.validity_until < todayISO);
    const weighted = leads.filter((l) => !["Won","Lost","Cancelled","Converted","Closed"].includes(l.status)).reduce((sum,l) => { const p={Urgent:.9,High:.75,Medium:.5,Low:.25}[l.priority] || .5; return sum + Number(l.expected_budget||0)*p; },0);
    return { stale: stale.length, overdue: overdue.length, quoteRisk: quoteRisk.length, weightedPipeline: weighted, risk: stale.length + overdue.length + quoteRisk.length };
  }, [leads, followUps, quotes, todayISO]);
  const sortedCustomers = useMemo(() => [...customer360].sort((a,b) => customerSort === "value" ? (b.revenue+b.pipeline)-(a.revenue+a.pipeline) : customerSort === "recent" ? new Date(b.lastActivity||0)-new Date(a.lastActivity||0) : ((b.nextFollowUp ? 1 : 0) - (a.nextFollowUp ? 1 : 0)) + ((b.leads.length)-(a.leads.length))), [customer360, customerSort]);
  const quoteStatus = async (q, next) => { await call("crm_update_quotation_status", { p_quote_id: q.id, p_status: next }); };
  const statusColumns = ["New", "Contacted", "Interested", "Quotation Sent", "Negotiation", "Won", "Lost"];
  const statCards = [["New leads", dashboard.newLeads, UserPlus], ["Hot leads", dashboard.hot, Flame], ["Today's follow-ups", dashboard.followUps, CalendarClock], ["Missed follow-ups", dashboard.missed, AlertTriangle], ["Won", dashboard.won, Trophy], ["Lost", dashboard.lost, XCircle], ["Revenue", money(dashboard.revenue), Coins], ["Conversion", `${dashboard.conversion}%`, GaugeCircle]];
  return (
    <div className="content">
      <div className="page-head"><div><h3>Leads & sales pipeline</h3><div className="hint-line">Lead → follow-up → quotation → project → revenue, connected to APN, finance, audit and notifications.</div></div><span className="spacer" /><button className="btn primary" onClick={() => setModal("lead")}><Plus size={16} />New lead</button></div>
      {error && <div className="auth-msg err" role="alert"><AlertTriangle size={15} />{error}<button className="iconbtn" style={{ marginLeft: "auto", width: 26, height: 26 }} onClick={() => setError("")} aria-label="Dismiss error"><X size={14} /></button></div>}
      <div className="seg" style={{ marginBottom: 16, overflowX: "auto" }}>{[["overview", "Overview"], ["pipeline", "Pipeline"], ["customers", "Customer 360"], ["leads", "Leads"], ["followups", "Follow-ups"], ["quotations", "Quotations"], ["revenue", "Revenue & projects"], ["activity", "Activity"]].map(([key, label]) => <button key={key} className={tab === key ? "on" : ""} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab === "overview" && <>
        <div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))", marginBottom: 16 }}>{statCards.map(([label, value, Icon]) => <div className="card stat" key={label}><div className="lbl"><Icon size={14} />{label}</div><div className="num mono">{value}</div></div>)}</div>
        <div className="cards-grid" style={{ gridTemplateColumns: "1.35fr 1fr", alignItems: "start" }}>
          <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Conversion funnel</div><div className="item-meta">Active {dashboard.active} · {leads.length} total leads</div></div><span className="badge pri">{dashboard.conversion}% conversion</span></div>{statusColumns.map((s) => { const n = leads.filter((l) => l.status === s).length; return <div key={s} className="item-row" style={{ padding: "10px 16px" }}><span style={{ flex: 1 }}>{s}</span><div className="progress-track" style={{ width: 140 }}><div className="progress-fill" style={{ width: `${leads.length ? Math.round(n * 100 / leads.length) : 0}%` }} /></div><span className="mono" style={{ width: 28, textAlign: "right" }}>{n}</span></div>; })}</div>
          <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Recent activity</div><div className="item-meta">Live CRM timeline</div></div><Activity size={16} color="var(--primary)" /></div>{(db.crm_activities || []).slice(0, 6).map((a) => <div className="item-row" key={a.id} style={{ padding: "10px 16px" }}><div className="item-main"><div style={{ fontWeight: 600 }}>{a.title}</div><div className="hint-line">{a.description}</div></div><span className="hint-line" style={{ whiteSpace: "nowrap" }}>{fmtDate(a.created_at)}</span></div>)}{!(db.crm_activities || []).length && <Empty icon={<Activity size={22} />} title="No CRM activity yet" text="Create a lead to start the lifecycle timeline." />}</div>
        </div>
      </>}
      {tab === "overview" && <div className="card" style={{ marginBottom: 16 }}><div className="item-row"><div className="item-main"><div className="item-title">CRM intelligence</div><div className="item-meta">Prioritise risk before it becomes lost revenue.</div></div><span className={`badge ${crmIntelligence.risk ? "neg" : "pos"}`}>{crmIntelligence.risk ? `${crmIntelligence.risk} risks` : "Healthy"}</span></div><div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))" }}><div className="card stat"><div className="lbl"><AlertTriangle size={14}/>Stale leads</div><div className="num mono">{crmIntelligence.stale}</div><div className="hint-line">No meaningful update for 7+ days</div></div><div className="card stat"><div className="lbl"><CalendarClock size={14}/>Overdue follow-ups</div><div className="num mono">{crmIntelligence.overdue}</div><div className="hint-line">Open actions past due</div></div><div className="card stat"><div className="lbl"><FileText size={14}/>Quote risk</div><div className="num mono">{crmIntelligence.quoteRisk}</div><div className="hint-line">Expired validity still in active status</div></div><div className="card stat"><div className="lbl"><GaugeCircle size={14}/>Weighted pipeline</div><div className="num mono">{money(crmIntelligence.weightedPipeline)}</div><div className="hint-line">Priority-weighted active pipeline</div></div></div></div>}
      {tab === "pipeline" && <><div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", marginBottom: 14 }}><div className="card stat"><div className="lbl"><FolderKanban size={14} />Open pipeline value</div><div className="num mono">{money(pipelineValue)}</div><div className="hint-line">{dashboard.active} active leads</div></div><div className="card stat"><div className="lbl"><FileText size={14} />Quote pipeline</div><div className="num mono">{money(quotePipelineValue)}</div><div className="hint-line">Excludes rejected/expired</div></div><div className="card stat"><div className="lbl"><CalendarClock size={14} />Follow-up coverage</div><div className="num mono">{dashboard.active ? Math.round(dashboard.followUps * 100 / dashboard.active) : 0}%</div><div className="hint-line">Open future follow-ups vs active leads</div></div></div><div className="crm-kanban">{statusColumns.map((s) => <div className="card" key={s} onDragOver={(e) => e.preventDefault()} onDrop={async () => { const l = leads.find((x) => x.id === dragId); if (l && l.status !== s) await updateStatus(l, s); setDragId(null); }}><div className="item-row" style={{ padding: "12px 14px" }}><div className="item-main"><div className="item-title">{s}</div><div className="item-meta">{leads.filter((l) => l.status === s).length} leads</div></div></div>{leads.filter((l) => l.status === s).map((l) => <div key={l.id} draggable onDragStart={() => setDragId(l.id)} className="crm-kanban-card" onClick={() => selectLead(l)}><div style={{ fontWeight: 700 }}>{l.customer_name}</div><div className="hint-line">{l.lead_number} · {l.project_category || "—"}</div><div className="item-meta"><span className={`badge ${l.priority === "Urgent" ? "neg" : l.priority === "High" ? "accent" : ""}`}>{l.priority}</span><span>{l.expected_budget ? money(l.expected_budget) : "Budget —"}</span></div></div>)}</div>)}</div></>}
      {tab === "customers" && <div className="cards-grid" style={{ gridTemplateColumns: "minmax(280px,0.8fr) minmax(0,1.6fr)", alignItems: "start" }}>
        <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">Customer directory</div><div className="item-meta">One customer view across leads, follow-ups, quotes, projects and collections.</div></div><span className="badge pri">{customer360.length}</span></div><div className="toolbar" style={{ margin: "10px 12px" }}><div className="search" style={{ flex: 1 }}><Search size={16} color="var(--muted)" /><input value={customerQuery} onChange={(e) => setCustomerQuery(e.target.value)} placeholder="Search customer, company, phone, email…" aria-label="Search CRM customers" /></div><select className="select" value={customerSort} onChange={(e) => setCustomerSort(e.target.value)}><option value="risk">Priority</option><option value="value">Value</option><option value="recent">Recent</option></select></div>{customer360.length ? sortedCustomers.map((g) => <button key={g.key} className="item-row" onClick={() => setSelectedCustomerKey(g.key)} style={{ width: "100%", textAlign: "left", background: selectedCustomer?.key === g.key ? "var(--surface-2)" : "transparent", border: 0, borderTop: "1px solid var(--border)", cursor: "pointer" }}><Avatar name={g.name} size={32} /><div className="item-main"><div style={{ fontWeight: 700 }}>{g.name}</div><div className="hint-line">{g.company || g.email || g.mobile || "No contact detail"}</div></div><ChevronRight size={15} /></button>) : <Empty icon={<UserPlus size={22} />} title="No customers found" text="Customers are grouped automatically from CRM lead contact details." />}</div>
        {selectedCustomer && <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">{selectedCustomer.name}</div><div className="item-meta">{selectedCustomer.company || "No company"} · {selectedCustomer.email || selectedCustomer.mobile || "No contact detail"}</div></div><ContactButtons person={{ name: selectedCustomer.name, mobile: selectedCustomer.mobile, email: selectedCustomer.email }} compact /></div><div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(135px,1fr))", margin: "12px 0" }}><div className="card stat"><div className="lbl"><UserPlus size={14} />Leads</div><div className="num mono">{selectedCustomer.leads.length}</div></div><div className="card stat"><div className="lbl"><FolderKanban size={14} />Pipeline</div><div className="num mono">{money(selectedCustomer.pipeline)}</div></div><div className="card stat"><div className="lbl"><FileText size={14} />Quotes</div><div className="num mono">{selectedCustomer.quotes.length}</div></div><div className="card stat"><div className="lbl"><Coins size={14} />Collected</div><div className="num mono">{money(selectedCustomer.revenue)}</div></div></div><div className="item-row"><div className="item-main"><div className="item-title">Relationship timeline</div><div className="item-meta">{selectedCustomer.projects.length} linked project(s) · {selectedCustomer.nextFollowUp ? `Next follow-up ${fmtDate(selectedCustomer.nextFollowUp.follow_up_date)}` : "No future follow-up"}</div></div><button className="btn sm" onClick={() => { const l = selectedCustomer.leads[0]; if (l) selectLead(l); }}>Open lead</button></div>{selectedCustomer.activities.length ? <div className="activity-timeline" style={{ padding: "0 16px 16px" }}>{selectedCustomer.activities.slice(0, 12).map((a) => <div className="activity-timeline-item" key={a.id}><div className="activity-timeline-dot" /><div><div style={{ fontWeight: 700 }}>{a.title || a.event_type || "CRM activity"}</div><div className="hint-line">{a.description || "No description"} · {fmtDateTime(a.created_at)} · {a.actor_name || "System"}</div></div></div>)}</div> : <Empty icon={<Activity size={22} />} title="No activity yet" text="New CRM lifecycle events will appear here." />}</div>}
      </div>}
      {tab === "activity" && <div className="card"><div className="item-row"><div className="item-main"><div className="item-title">CRM activity timeline</div><div className="item-meta">One chronological audit-friendly stream across lead lifecycle actions.</div></div><span className="badge pri">{visibleActivities.length} events</span></div><div className="toolbar" style={{ marginBottom: 12 }}><div className="search"><Search size={16} color="var(--muted)" /><input value={activityQuery} onChange={(e) => setActivityQuery(e.target.value)} placeholder="Search activity, lead, actor, description…" aria-label="Search CRM activity" /></div><select className="select" value={activityType} onChange={(e) => setActivityType(e.target.value)} style={{ width: "auto" }}>{activityTypes.map((x) => <option key={x}>{x}</option>)}</select></div>{visibleActivities.length ? <div className="activity-timeline">{visibleActivities.map((a) => <div className="activity-timeline-item" key={a.id}><div className="activity-timeline-dot" /><div style={{ minWidth: 0 }}><div style={{ fontWeight: 700 }}>{a.title || a.event_type || "CRM activity"}</div><div className="hint-line">{a.description || "No description"}</div><div className="hint-line" style={{ marginTop: 4 }}>{a.actor_name || "System"} · {fmtDateTime(a.created_at)}{a.event_type ? ` · ${a.event_type}` : ""}</div></div></div>)}</div> : <Empty icon={<Activity size={22} />} title="No matching activity" text="CRM lifecycle actions will appear here as leads, follow-ups, quotations and revenue change." />}</div>}
      {tab === "leads" && <>
        <div className="toolbar"><div className="search"><Search size={16} color="var(--muted)" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search ID, customer, company, phone, owner, district, state, tags…" aria-label="Search CRM leads" /></div><select className="select" value={status} onChange={(e) => setStatus(e.target.value)} style={{ width: "auto" }}><option>All</option>{["New","Assigned","Contacted","Follow-up","Interested","Quotation Sent","Negotiation","Won","Lost","On Hold","Cancelled","Converted","Closed"].map((s) => <option key={s}>{s}</option>)}</select><select className="select" value={priority} onChange={(e) => setPriority(e.target.value)} style={{ width: "auto" }}><option>All</option>{PRIORITIES.map((p) => <option key={p}>{p}</option>)}</select></div>
        <div className="card"><div className="table-wrap">{visibleLeads.length ? <table className="tbl"><thead><tr><th>Lead</th><th>Contact</th><th>Source</th><th>Owner / partner</th><th>Budget</th><th>Status</th><th></th></tr></thead><tbody>{visibleLeads.map((l) => <tr key={l.id} onClick={() => selectLead(l)} style={{ cursor: "pointer" }}><td><div style={{ fontWeight: 700 }}>{l.customer_name}</div><div className="hint-line">{l.lead_number}{l.company ? ` · ${l.company}` : ""}</div></td><td>{l.mobile || "—"}<div className="hint-line">{l.email || ""}</div></td><td><span className="badge pri">{l.source}</span></td><td><select className="select" value={l.assigned_employee_id || ""} onClick={(e) => e.stopPropagation()} onChange={(e) => assign(l, e.target.value, l.assigned_partner_id)} style={{ minWidth: 140, padding: "5px 8px" }}><option value="">Unassigned</option>{employees.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{l.assigned_partner_id && <div className="hint-line">APN: {(partners.find((p) => p.id === l.assigned_partner_id)?.name) || l.assigned_partner_id}</div>}</td><td className="mono">{money(l.expected_budget)}</td><td><select className="select" value={l.status} onClick={(e) => e.stopPropagation()} onChange={(e) => updateStatus(l, e.target.value)} style={{ width: "auto", padding: "5px 8px" }}>{["New","Assigned","Contacted","Follow-up","Interested","Quotation Sent","Negotiation","Won","Lost","On Hold","Cancelled","Converted","Closed"].map((s) => <option key={s}>{s}</option>)}</select></td><td><button className="btn sm" onClick={(e) => { e.stopPropagation(); setSelected(l); setModal("follow"); }}><CalendarClock size={13} />Follow-up</button></td></tr>)}</tbody></table> : <Empty icon={<UserPlus size={22} />} title={query || status !== "All" ? "No matching leads" : "No leads yet"} text="Capture a lead once and keep every next step linked to the same record." action={!query && <button className="btn primary" onClick={() => setModal("lead")}><Plus size={16} />Create first lead</button>} />}</div></div>
      </>}
      {tab === "followups" && <div className="card"><div className="table-wrap">{followUps.length ? <table className="tbl"><thead><tr><th>Date / time</th><th>Lead</th><th>Priority</th><th>Notes</th><th>Status</th></tr></thead><tbody>{followUps.map((f) => { const l = leads.find((x) => x.id === f.lead_id); return <tr key={f.id}><td className="mono">{fmtDate(f.follow_up_date)}{f.follow_up_time ? ` · ${f.follow_up_time}` : ""}</td><td><button className="linkbtn" style={{ margin: 0 }} onClick={() => l && selectLead(l)}>{l?.customer_name || "—"}</button><div className="hint-line">{l?.lead_number}</div></td><td><span className={`badge ${f.priority === "Urgent" || f.priority === "High" ? "neg" : "accent"}`}>{f.priority}</span></td><td>{f.notes || "—"}</td><td><span className={`badge ${f.status === "Completed" ? "pos" : f.follow_up_date < todayISO() ? "neg" : "pri"}`}>{f.status === "Open" && f.follow_up_date < todayISO() ? "Missed" : f.status}</span></td></tr>; })}</tbody></table> : <Empty icon={<CalendarClock size={22} />} title="No follow-ups scheduled" text="Open any lead and schedule a call, reminder, or next action." />}</div></div>}
      {tab === "quotations" && <div className="cards-grid" style={{ gridTemplateColumns: "repeat(auto-fill,minmax(310px,1fr))" }}>{quotes.length ? quotes.map((q) => <div className="card stat" key={q.id}><div style={{ display: "flex", gap: 8 }}><div className="item-main"><div className="item-title">{q.title}</div><div className="item-meta">{q.quote_number} · {leads.find((l) => l.id === q.lead_id)?.customer_name || "—"}</div></div><div className="mono" style={{ fontWeight: 700 }}>{money(q.grand_total)}</div></div><div className="item-meta"><span className={`badge ${q.status === "Accepted" || q.status === "Converted" ? "pos" : q.status === "Rejected" ? "neg" : "pri"}`}>{q.status}</span><span>Valid until {q.validity_until ? fmtDate(q.validity_until) : "—"}</span></div><div className="row-actions"><select className="select" value={q.status} onChange={(e) => quoteStatus(q, e.target.value)} style={{ width: "auto", padding: "5px 8px" }}>{["Draft","Pending Approval","Approved","Sent","Viewed","Accepted","Rejected","Expired","Converted"].map((s) => <option key={s}>{s}</option>)}</select></div></div>) : <div className="card" style={{ gridColumn: "1/-1" }}><Empty icon={<FileText size={22} />} title="No CRM quotations" text="Create a quotation from a lead to keep versions, approval and conversion linked." /></div>}</div>}
      {tab === "revenue" && <div className="card"><div className="table-wrap">{projects.length ? <table className="tbl"><thead><tr><th>Project</th><th>Lead</th><th>Value</th><th>Revenue</th><th>APN / commission</th><th></th></tr></thead><tbody>{projects.map((p) => { const l = leads.find((x) => x.id === p.lead_id); const rev = revenue.filter((r) => r.project_id === p.id); return <tr key={p.id}><td><div style={{ fontWeight: 700 }}>{p.name}</div><div className="hint-line">{p.project_number} · {p.status}</div></td><td>{l?.customer_name || "—"}</td><td className="mono">{money(p.project_value)}</td><td className="mono">{money(rev.reduce((s, r) => s + Number(r.received_amount || 0), 0))}</td><td>{p.assigned_partner_id ? <span className="badge accent">APN linked</span> : <span className="hint-line">Direct</span>}{rev.length > 0 && <div className="hint-line">{money(rev.reduce((s, r) => s + Number(r.commission_generated || 0), 0))} commission</div>}</td><td>{l && <button className="btn sm primary" onClick={() => { setSelected(l); setModal("revenue"); }}>Record collection</button>}</td></tr>; })}</tbody></table> : <Empty icon={<FolderKanban size={22} />} title="No converted projects" text="Accept a quotation to create a project and connect future revenue automatically." />}</div></div>}
      {selected && <div className="card" style={{ marginTop: 16 }}><div className="item-row"><div className="item-main"><div className="item-title">{selected.customer_name} <span className="badge pri" style={{ marginLeft: 6 }}>{selected.lead_number}</span></div><div className="item-meta">{selected.company || "No company"} · {selected.status} · {selected.source}</div></div><ContactButtons person={{ name: selected.customer_name, mobile: selected.mobile, email: selected.email }} compact /><button className="iconbtn" onClick={() => setSelected(null)} aria-label="Close lead details"><X size={15} /></button></div><div className="item-row" style={{ alignItems: "flex-start", flexWrap: "wrap" }}><div className="item-main"><div className="hint-line">{selected.address || selected.location || "No address"}{selected.district ? ` · ${selected.district}` : ""}{selected.state ? ` · ${selected.state}` : ""}</div><div className="item-meta">Budget {money(selected.expected_budget)} · Score {selected.lead_score}/100 · Priority {selected.priority}</div></div><div className="row-actions"><button className="btn sm" onClick={() => setModal("follow")}><CalendarClock size={13} />Schedule follow-up</button><button className="btn sm" onClick={() => setModal("quote")}><FileText size={13} />Create quotation</button>{selected.project_id && <button className="btn sm primary" onClick={() => setModal("revenue")}><Coins size={13} />Record revenue</button>}</div></div><div className="activity-timeline" style={{ padding: "0 16px 16px" }}>{activityFor(selected.id).map((a) => <div className="activity-timeline-item" key={a.id}><div className="activity-timeline-dot" /><div><div style={{ fontWeight: 600 }}>{a.title}</div><div className="hint-line">{a.description} · {fmtDate(a.created_at)} · {a.actor_name || "System"}</div></div></div>)}</div></div>}
      {modal === "lead" && <Modal title="Create CRM lead" onClose={() => setModal(null)} onMaximize={() => {}} footer={<><button className="btn" onClick={() => setModal(null)}>Cancel</button><button className="btn primary" disabled={busy} onClick={saveLead}>{busy ? "Saving…" : "Create lead"}</button></>}><div className="grid2"><Field label="Customer name" required><input className="input" autoFocus value={leadForm.customer_name} onChange={(e) => setLeadForm({ ...leadForm, customer_name: e.target.value })} /></Field><Field label="Company"><input className="input" value={leadForm.company} onChange={(e) => setLeadForm({ ...leadForm, company: e.target.value })} /></Field><Field label="Mobile"><input className="input" value={leadForm.mobile} onChange={(e) => setLeadForm({ ...leadForm, mobile: e.target.value })} /></Field><Field label="Email"><input className="input" type="email" value={leadForm.email} onChange={(e) => setLeadForm({ ...leadForm, email: e.target.value })} /></Field><Field label="Lead source"><select className="select" value={leadForm.source} onChange={(e) => setLeadForm({ ...leadForm, source: e.target.value })}>{["Website","WhatsApp","Instagram","Facebook","Walk-in","Phone Call","Referral","Existing Client","APN Referral","Employee Referral","Manual Entry"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Project category"><select className="select" value={leadForm.project_category} onChange={(e) => setLeadForm({ ...leadForm, project_category: e.target.value })}>{["Website","Mobile App","Software","Marketing","Training","AMC","Custom Services"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Expected budget"><input className="input" type="number" min="0" value={leadForm.expected_budget} onChange={(e) => setLeadForm({ ...leadForm, expected_budget: e.target.value })} /></Field><Field label="Expected closing date"><input className="input" type="date" value={leadForm.expected_closing_date} onChange={(e) => setLeadForm({ ...leadForm, expected_closing_date: e.target.value })} /></Field><Field label="Priority"><select className="select" value={leadForm.priority} onChange={(e) => setLeadForm({ ...leadForm, priority: e.target.value })}>{PRIORITIES.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="District"><input className="input" value={leadForm.district} onChange={(e) => setLeadForm({ ...leadForm, district: e.target.value })} /></Field></div><Field label="Remarks"><textarea className="textarea" value={leadForm.remarks} onChange={(e) => setLeadForm({ ...leadForm, remarks: e.target.value })} /></Field><Field label="Tags" hint="Comma-separated"><input className="input" value={leadForm.tags} onChange={(e) => setLeadForm({ ...leadForm, tags: e.target.value })} placeholder="website, hot, referral" /></Field></Modal>}
      {modal === "follow" && <Modal title={`Schedule follow-up · ${selected?.customer_name || "Lead"}`} onClose={() => setModal(null)} footer={<><button className="btn" onClick={() => setModal(null)}>Cancel</button><button className="btn primary" disabled={busy} onClick={addFollowUp}>Schedule</button></>}><div className="grid2"><Field label="Date" required><input className="input" type="date" value={followForm.follow_up_date} onChange={(e) => setFollowForm({ ...followForm, follow_up_date: e.target.value })} /></Field><Field label="Time"><input className="input" type="time" value={followForm.follow_up_time} onChange={(e) => setFollowForm({ ...followForm, follow_up_time: e.target.value })} /></Field><Field label="Priority"><select className="select" value={followForm.priority} onChange={(e) => setFollowForm({ ...followForm, priority: e.target.value })}>{PRIORITIES.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Next follow-up"><input className="input" type="date" value={followForm.next_follow_up} onChange={(e) => setFollowForm({ ...followForm, next_follow_up: e.target.value })} /></Field></div><Field label="Notes"><textarea className="textarea" value={followForm.notes} onChange={(e) => setFollowForm({ ...followForm, notes: e.target.value })} autoFocus /></Field></Modal>}
      {modal === "quote" && <Modal title={`Create quotation · ${selected?.customer_name || "Lead"}`} onClose={() => setModal(null)} footer={<><button className="btn" onClick={() => setModal(null)}>Cancel</button><button className="btn primary" disabled={busy} onClick={createQuote}>Create quotation</button></>}><div className="grid2"><Field label="Title" required><input className="input" autoFocus value={quoteForm.title} onChange={(e) => setQuoteForm({ ...quoteForm, title: e.target.value })} placeholder="Website development proposal" /></Field><Field label="Service"><select className="select" value={quoteForm.service_type} onChange={(e) => setQuoteForm({ ...quoteForm, service_type: e.target.value })}>{["Website","Mobile App","Software","Marketing","Training","AMC","Custom Services"].map((x) => <option key={x}>{x}</option>)}</select>{quotePricingBusy ? <div className="hint-line">Loading official pricing…</div> : <div className="hint-line">{quotePricing?.base != null ? `Official starting price: ${money(quotePricing.base)}` : "Custom quotation — confirm after scope review."}</div>}</Field><Field label="Item description"><input className="input" value={quoteForm.description} onChange={(e) => setQuoteForm({ ...quoteForm, description: e.target.value })} /></Field><Field label="Quantity"><input className="input" type="number" min="1" value={quoteForm.quantity} onChange={(e) => setQuoteForm({ ...quoteForm, quantity: e.target.value })} /></Field><Field label="Unit price"><input className="input" type="number" min="0" value={quoteForm.unit_price} onChange={(e) => setQuoteForm({ ...quoteForm, unit_price: e.target.value })} /></Field><Field label="Discount"><input className="input" type="number" min="0" value={quoteForm.discount} onChange={(e) => setQuoteForm({ ...quoteForm, discount: e.target.value })} /></Field><Field label="GST %"><input className="input" type="number" min="0" value={quoteForm.gst} onChange={(e) => setQuoteForm({ ...quoteForm, gst: e.target.value })} /></Field><Field label="Validity"><input className="input" type="date" value={quoteForm.validity_until} onChange={(e) => setQuoteForm({ ...quoteForm, validity_until: e.target.value })} /></Field></div></Modal>}
      {modal === "revenue" && <Modal title={`Record revenue · ${selected?.customer_name || "Project"}`} onClose={() => setModal(null)} footer={<><button className="btn" onClick={() => setModal(null)}>Cancel</button><button className="btn primary" disabled={busy} onClick={recordRevenue}>Record collection</button></>}><div className="grid2"><Field label="Amount" required><input className="input" type="number" min="0.01" autoFocus value={revenueForm.amount} onChange={(e) => setRevenueForm({ ...revenueForm, amount: e.target.value })} /></Field><Field label="Received date"><input className="input" type="date" value={revenueForm.received_at} onChange={(e) => setRevenueForm({ ...revenueForm, received_at: e.target.value })} /></Field><Field label="Incentive"><input className="input" type="number" min="0" value={revenueForm.incentive} onChange={(e) => setRevenueForm({ ...revenueForm, incentive: e.target.value })} /></Field></div><Field label="Remarks"><textarea className="textarea" value={revenueForm.remarks} onChange={(e) => setRevenueForm({ ...revenueForm, remarks: e.target.value })} /></Field><div className="hint-line">This creates the CRM collection and automatically links finance, APN commission, direct referral earnings, timeline, audit, and notifications.</div></Modal>}
    </div>
  );
}
