import React, { useState, useEffect, useCallback } from "react";

export function proposalSectionDisplay(section, money) {
  const c = section?.content || {};
  if (c.text) return c.text;
  if (c.items && Array.isArray(c.items)) return c.items.map((x) => typeof x === "string" ? x : (x.label || x.name || x.title || x.description || JSON.stringify(x))).filter(Boolean).join("\n");
  if (c.estimate) return c.estimate.estimated_cost != null ? `Estimated value: ${money(c.estimate.estimated_cost)}` : (c.estimate.disclaimer || "Custom quotation");
  return Object.entries(c).filter(([, value]) => value != null && value !== "").map(([key, value]) => `${key.replace(/_/g, " ")}: ${typeof value === "object" ? JSON.stringify(value) : value}`).join("\n");
}
function escapeProposalHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
export function printProposalDocument(detail, runtime) {
  const { money } = runtime;
  const p = detail?.proposal || detail;
  const sections = detail?.sections || [];
  const w = window.open("", "_blank");
  if (!w) return;
  const body = sections.filter((s) => s.enabled !== false).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0)).map((s) => `<section><h2>${escapeProposalHtml(s.name)}</h2><div class="section-body">${escapeProposalHtml(proposalSectionDisplay(s, runtime.money)).replace(/\n/g, "<br>")}</div></section>`).join("");
  w.document.write(`<!doctype html><html><head><title>${escapeProposalHtml(p.proposal_number || "Proposal")}</title><style>@page{margin:18mm}body{font-family:Arial,sans-serif;color:#172033;max-width:820px;margin:auto;line-height:1.5}header{border-bottom:3px solid #2e3b8f;padding-bottom:16px;margin-bottom:24px}h1{color:#2e3b8f;margin:0}h2{font-size:18px;color:#2e3b8f;border-bottom:1px solid #dfe4ee;padding-bottom:6px;margin-top:26px}.muted{color:#687386;font-size:12px}.section-body{white-space:normal}.summary{background:#f5f7fb;border:1px solid #dfe4ee;border-radius:10px;padding:14px;margin-top:16px}.total{font-size:20px;font-weight:800;color:#15245f}</style></head><body><header><h1>ALLBEE SOLUTIONS</h1><div class="muted">Enterprise business proposal · ${escapeProposalHtml(p.proposal_number || "")}</div><h3>${escapeProposalHtml(p.proposal_title || "Business proposal")}</h3><div class="muted">Prepared for ${escapeProposalHtml(p.customer_name || "Customer")} · Version ${escapeProposalHtml(p.current_version || 1)}</div></header><div class="summary"><b>Proposal value</b><div class="total">${money(p.grand_total || 0)}</div><div class="muted">Pricing mode: ${escapeProposalHtml(p.pricing_mode || "estimated")} · Status: ${escapeProposalHtml(p.status || "draft")}</div></div>${body}<footer class="muted" style="margin-top:36px;border-top:1px solid #dfe4ee;padding-top:10px">Generated from the approved AllBee knowledge and requirement engines.</footer><script>window.onload=function(){window.print()}</script></body></html>`);
  w.document.close();
}

export default function ProposalCenter({ isAdmin, runtime }) {
  const { supabase, emitToast, money, Empty, Modal, Search, RefreshCw, AlertTriangle, FileText, ShieldAlert, Eye, Pencil, Activity, Download, Copy, Send, Check } = runtime;
  const [tab, setTab] = useState("proposals");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [data, setData] = useState({ items: [], total: 0 });
  const [summary, setSummary] = useState(null);
  const [selected, setSelected] = useState(null);
  const [sections, setSections] = useState([]);
  const [editor, setEditor] = useState(null);
  const [editorText, setEditorText] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    if (!isAdmin) return;
    setBusy(true); setError("");
    try {
      const [{ data: list, error: listError }, { data: counts, error: summaryError }] = await Promise.all([
        supabase.rpc("proposal_admin_list", { p_search: query, p_status: status, p_limit: 100, p_offset: 0 }),
        supabase.rpc("proposal_admin_summary"),
      ]);
      if (listError) throw new Error(listError.message);
      if (summaryError) throw new Error(summaryError.message);
      setData(list || { items: [], total: 0 }); setSummary(counts || {});
      if (tab === "sections") { const { data: defs, error: defError } = await supabase.from("proposal_section_definitions").select("*").order("sort_order"); if (defError) throw new Error(defError.message); setSections(defs || []); }
    } catch (e) { setError(e.message || "Proposal Center could not load."); }
    finally { setBusy(false); }
  }, [isAdmin, query, status, tab]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const ch = supabase.channel("proposal-center").on("postgres_changes", { event: "*", schema: "public", table: "proposals" }, load).on("postgres_changes", { event: "*", schema: "public", table: "proposal_versions" }, load).on("postgres_changes", { event: "*", schema: "public", table: "proposal_analytics" }, load).on("postgres_changes", { event: "*", schema: "public", table: "proposal_section_definitions" }, load).subscribe(); return () => supabase.removeChannel(ch); }, [load]);
  const openProposal = async (id) => { setBusy(true); setError(""); try { const { data: detail, error: rpcError } = await supabase.rpc("proposal_get", { p_proposal_id: id }); if (rpcError) throw new Error(rpcError.message); setSelected(detail); } catch (e) { setError(e.message || "Proposal could not load."); } finally { setBusy(false); } };
  const action = async (name, comment = "") => { if (!selected?.proposal?.id) return; setBusy(true); setError(""); try { const { data: detail, error: rpcError } = await supabase.rpc("proposal_record_action", { p_proposal_id: selected.proposal.id, p_action: name, p_comment: comment, p_token: null, p_signer_name: null, p_signer_email: null, p_signature: null }); if (rpcError) throw new Error(rpcError.message); setSelected(detail); await load(); emitToast(`Proposal ${name.replace(/_/g, " ")}.`, "success"); } catch (e) { setError(e.message || "Proposal action failed."); } finally { setBusy(false); } };
  const share = async () => { if (!selected?.proposal?.id) return; setBusy(true); try { const { data: link, error: rpcError } = await supabase.rpc("proposal_regenerate_public_link", { p_proposal_id: selected.proposal.id }); if (rpcError) throw new Error(rpcError.message); const url = `${window.location.origin}${window.location.pathname}#/proposal/${link.public_token}`; await navigator.clipboard?.writeText(url); emitToast("Customer proposal link copied.", "success"); } catch (e) { setError(e.message || "Could not create proposal link."); } finally { setBusy(false); } };
  const saveSection = async () => { let payload; try { payload = JSON.parse(editorText); } catch { setError("Enter valid JSON."); return; } setBusy(true); try { const { error: rpcError } = await supabase.rpc("proposal_save_section_definition", { p_payload: payload }); if (rpcError) throw new Error(rpcError.message); setEditor(null); await load(); emitToast("Proposal section saved.", "success"); } catch (e) { setError(e.message || "Section could not save."); } finally { setBusy(false); } };
  if (!isAdmin) return <div className="content"><div className="card"><Empty icon={<ShieldAlert size={22} />} title="Admin access required" text="Proposal Center is restricted to administrators." /></div></div>;
  return <div className="content">
    <div className="page-head"><div><h3><FileText size={18} style={{ verticalAlign: -3, marginRight: 7, color: "var(--primary)" }} />Proposal Center</h3><div className="hint-line">Enterprise proposals generated from completed requirements and the approved knowledge catalog.</div></div><span className="spacer" /><button className="btn" onClick={load} disabled={busy}><RefreshCw size={14} className={busy ? "spin" : ""} />Refresh</button></div>
    {error && <div className="auth-msg err" role="alert"><AlertTriangle size={15} />{error}</div>}
    <div className="ai-health-grid" style={{ marginBottom: 14 }}>{[["Created", summary?.created], ["Viewed", summary?.viewed], ["Approved", summary?.approved], ["Avg value", summary?.average_value != null ? money(summary.average_value) : "—"], ["Conversion", `${summary?.conversion_rate || 0}%`]].map(([label, value]) => <div className="card stat" key={label}><div className="lbl"><FileText size={14} />{label}</div><div className="num mono">{value ?? "—"}</div></div>)}</div>
    <div className="seg" style={{ marginBottom: 12 }}>{[["proposals", "Proposals"], ["sections", "Section Builder"], ["analytics", "Analytics"]].map(([key, label]) => <button key={key} className={tab === key ? "on" : ""} onClick={() => setTab(key)}>{label}</button>)}</div>
    {tab === "proposals" && <><div className="toolbar"><div className="search"><Search size={16} color="var(--muted)" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search proposal, customer, service…" aria-label="Search proposals" /></div><select className="select" value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter proposals by status"><option value="">All statuses</option>{["draft", "sent", "viewed", "revision_requested", "approved", "rejected", "converted"].map((x) => <option key={x} value={x}>{x.replace(/_/g, " ")}</option>)}</select></div><div className="card">{data.items?.length ? <div className="table-wrap"><table className="tbl"><thead><tr><th>Proposal</th><th>Customer</th><th>Status</th><th>Value</th><th>Version</th><th></th></tr></thead><tbody>{data.items.map((row) => <tr key={row.id}><td><button className="linkbtn" onClick={() => openProposal(row.id)}><b>{row.proposal_number}</b></button><div className="hint-line">{row.proposal_title}</div></td><td>{row.customer_name || "—"}<div className="hint-line">{row.service_slug || "—"}</div></td><td><span className={`badge ${["approved", "converted"].includes(row.status) ? "pos" : row.status === "rejected" ? "neg" : "pri"}`}>{row.status}</span></td><td className="mono">{money(row.grand_total || 0)}</td><td>V{row.current_version}</td><td><button className="btn sm" onClick={() => openProposal(row.id)}><Eye size={13} />Open</button></td></tr>)}</tbody></table></div> : <Empty icon={<FileText size={22} />} title="No proposals yet" text="Complete a Requirement Discovery conversation to generate the first proposal." />}</div></>}
    {tab === "sections" && <div className="card"><div className="hint-line" style={{ marginBottom: 10 }}>Template sections are modular and database-configured. Disable or rename a section without changing proposal generation.</div>{sections.length ? <div className="table-wrap"><table className="tbl"><thead><tr><th>Section</th><th>Type</th><th>Order</th><th>Status</th><th></th></tr></thead><tbody>{sections.map((row) => <tr key={row.id}><td><b>{row.name}</b><div className="hint-line mono">{row.section_key}</div></td><td>{row.section_type}</td><td>{row.sort_order}</td><td><span className={`badge ${row.enabled ? "pos" : "neg"}`}>{row.enabled ? "Enabled" : "Archived"}</span></td><td><button className="btn sm" onClick={() => { setEditor(row); setEditorText(JSON.stringify(row, null, 2)); }}><Pencil size={13} />Edit</button></td></tr>)}</tbody></table></div> : <Empty icon={<FileText size={22} />} title="No section definitions" text="The proposal template has no active sections." />}</div>}
    {tab === "analytics" && <div className="card"><div className="hint-line">Tracked proposal events include creation, views, downloads, shares, approvals, rejections, and revision requests.</div><div className="cards-grid" style={{ marginTop: 14 }}>{Object.entries(summary || {}).filter(([k]) => !["average_value", "conversion_rate"].includes(k)).map(([key, value]) => <div className="card stat" key={key}><div className="lbl"><Activity size={14} />{key.replace(/_/g, " ")}</div><div className="num mono">{value ?? 0}</div></div>)}</div></div>}
    {selected && <Modal title={`${selected.proposal?.proposal_number || "Proposal"} · V${selected.proposal?.current_version || 1}`} onClose={() => setSelected(null)} footer={<><button className="btn" onClick={() => printProposalDocument(selected, runtime)}><Download size={14} />Print / PDF</button><button className="btn" onClick={share}><Copy size={14} />Customer link</button><span className="spacer" /><button className="btn" onClick={() => action("revision_requested")} disabled={busy}>Request revision</button><button className="btn primary" onClick={() => action("sent")} disabled={busy}><Send size={14} />Send proposal</button></>}><div className="proposal-preview"><div className="proposal-preview-head"><div><div className="hint-line">{selected.proposal?.service_slug || "Business solution"}</div><h2 style={{ margin: "4px 0" }}>{selected.proposal?.proposal_title}</h2><div className="hint-line">Prepared for {selected.proposal?.customer_name || "Customer"} · {selected.proposal?.pricing_mode || "estimated"}</div></div><strong className="mono">{money(selected.proposal?.grand_total || 0)}</strong></div>{(selected.sections || []).map((section) => <div className="proposal-preview-section" key={section.id}><b>{section.name}</b><div className="hint-line" style={{ whiteSpace: "pre-wrap", marginTop: 4 }}>{proposalSectionDisplay(section, runtime.money) || "—"}</div></div>)}</div></Modal>}
    {editor && <Modal title="Edit proposal section" onClose={() => setEditor(null)} footer={<><button className="btn" onClick={() => setEditor(null)}>Cancel</button><button className="btn primary" onClick={saveSection} disabled={busy}><Check size={14} />Save section</button></>}><p className="hint-line">Section definitions are stored in the proposal template catalog and applied to future versions.</p><textarea className="textarea mono" style={{ minHeight: 300, fontSize: 12 }} value={editorText} onChange={(e) => setEditorText(e.target.value)} aria-label="Proposal section JSON" /></Modal>}
  </div>;
}

