export function proposalSectionDisplay(section, money) {
  const c = section?.content || {};
  if (c.text) return c.text;
  if (c.items && Array.isArray(c.items)) return c.items.map((x) => typeof x === "string" ? x : (x.label || x.name || x.title || x.description || JSON.stringify(x))).filter(Boolean).join("\n");
  if (c.estimate) return c.estimate.estimated_cost != null ? `Estimated value: ${money(c.estimate.estimated_cost)}` : (c.estimate.disclaimer || "Custom quotation");
  return Object.entries(c).filter(([, value]) => value != null && value !== "").map(([key, value]) => `${key.replace(/_/g, " ")}: ${typeof value === "object" ? JSON.stringify(value) : value}`).join("\n");
}
function escapeProposalHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
export function printProposalDocument(detail, runtime) {
  const { money } = runtime; const p = detail?.proposal || detail; const sections = detail?.sections || []; const w = window.open("", "_blank"); if (!w) return;
  const body = sections.filter((s) => s.enabled !== false).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0)).map((s) => `<section><h2>${escapeProposalHtml(s.name)}</h2><div class="section-body">${escapeProposalHtml(proposalSectionDisplay(s, money)).replace(/\n/g, "<br>")}</div></section>`).join("");
  w.document.write(`<!doctype html><html><head><title>${escapeProposalHtml(p.proposal_number || "Proposal")}</title><style>@page{margin:18mm}body{font-family:Arial,sans-serif;color:#172033;max-width:820px;margin:auto;line-height:1.5}header{border-bottom:3px solid #2e3b8f;padding-bottom:16px;margin-bottom:24px}h1{color:#2e3b8f;margin:0}h2{font-size:18px;color:#2e3b8f;border-bottom:1px solid #dfe4ee;padding-bottom:6px;margin-top:26px}.muted{color:#687386;font-size:12px}.section-body{white-space:normal}.summary{background:#f5f7fb;border:1px solid #dfe4ee;border-radius:10px;padding:14px;margin-top:16px}.total{font-size:20px;font-weight:800;color:#15245f}</style></head><body><header><h1>ALLBEE SOLUTIONS</h1><div class="muted">Enterprise business proposal · ${escapeProposalHtml(p.proposal_number || "")}</div><h3>${escapeProposalHtml(p.proposal_title || "Business proposal")}</h3><div class="muted">Prepared for ${escapeProposalHtml(p.customer_name || "Customer")} · Version ${escapeProposalHtml(p.current_version || 1)}</div></header><div class="summary"><b>Proposal value</b><div class="total">${money(p.grand_total || 0)}</div><div class="muted">Pricing mode: ${escapeProposalHtml(p.pricing_mode || "estimated")} · Status: ${escapeProposalHtml(p.status || "draft")}</div></div>${body}<footer class="muted" style="margin-top:36px;border-top:1px solid #dfe4ee;padding-top:10px">Generated from the approved AllBee knowledge and requirement engines.</footer><script>window.onload=function(){window.print()}</script></body></html>`); w.document.close();
}
