import { describe, expect, it } from "vitest";
import { createDataReaders } from "./data/readers.js";
import { NAV } from "./app/navigation.js";

describe("route data reader contract", () => {
  it("returns scoped table names for every known route", () => {
    const { routeDataTables, knownRoutes, apnTabs } = createDataReaders({
      supabase: {},
      emptyDB: () => ({}),
      loadTableRows: async () => [],
    });

    expect(NAV.map(([key]) => key).filter((key) => !knownRoutes.includes(key))).toEqual([]);
    expect(routeDataTables("dashboard")).toContain("notifications");
    expect(routeDataTables("dashboard")).toContain("tasks");
    expect(routeDataTables("accounts")).toContain("notifications");
    expect(routeDataTables("accounts")).toContain("transactions");
    expect(routeDataTables("assistant", "superadmin")).toEqual(expect.arrayContaining(["clients", "leads", "quotations", "invoices", "projects", "tasks", "class_students", "students", "marketing", "concepts", "inhouse", "planned", "apn_users", "transactions", "withdrawals", "audit", "attendance", "leave", "updates", "team_chat", "notifications", "rewards"]));
    expect(routeDataTables("ai-center", "superadmin")).toEqual(expect.arrayContaining(["crm_leads", "crm_follow_ups", "crm_quotations"]));
    expect(routeDataTables("withdrawals")).toContain("withdrawals");
    expect(routeDataTables("planned")).toContain("planned");
    expect(routeDataTables("staff-salary")).toContain("payroll");
    expect(routeDataTables("recently-deleted")).toContain("recycle");
    expect(routeDataTables("audit")).toContain("audit");
    expect(routeDataTables("myteam")).toContain("teams");
    expect(routeDataTables("myteam", "staff")).toContain("leave");
    expect(routeDataTables("attendance", "staff")).toContain("leave");
    expect(routeDataTables("prompts")).toContain("prompts");
    expect(routeDataTables("finance")).toContain("apn_withdrawal_requests");
    expect(routeDataTables("apnadmin")).toContain("apn_action_badge_reads");
    expect(routeDataTables("unknown-route")).toEqual(routeDataTables("dashboard"));
    expect(routeDataTables("dashboard", "partner")).toContain("apn_users");
    expect(routeDataTables("dashboard", "partner")).toContain("apn_zone_requests");
    expect(routeDataTables("dashboard", "partner")).toContain("apn_commission_projects");
    expect(routeDataTables("dashboard", "partner")).not.toContain("transactions");
    expect(routeDataTables("dashboard", "staff")).not.toContain("apn_users");
    expect(routeDataTables("dashboard", "staff")).not.toContain("apn_consolidated_wallets");
    expect(routeDataTables("dashboard", "staff")).toContain("students");
    expect(routeDataTables("earnings", "staff")).toContain("students");
    expect(routeDataTables("staff-salary", "superadmin")).toContain("students");
    expect(routeDataTables("dashboard", "superadmin")).toContain("apn_consolidated_wallets");
    expect(routeDataTables("dashboard", "accountant")).toContain("withdrawals");
    expect(routeDataTables("dashboard", "superadmin")).toContain("apn_commission_projects");
    expect(routeDataTables("dashboard", "superadmin")).toContain("apn_revenue_collections");
    expect(routeDataTables("dashboard", "superadmin")).toContain("audit");
    expect(routeDataTables("dashboard", "admin")).toContain("apn_commission_projects");
    expect(routeDataTables("dashboard", "admin")).toContain("apn_revenue_collections");
    expect(routeDataTables("dashboard", "admin")).toContain("apn_consolidated_wallets");
    expect(routeDataTables("dashboard", "staff")).not.toContain("apn_commission_projects");
    expect(routeDataTables("dashboard", "accountant")).not.toContain("apn_commission_projects");
    expect(routeDataTables("accounts", "accountant")).toContain("apn_consolidated_wallets");
    expect(routeDataTables("leads", "admin")).toEqual(expect.arrayContaining(["crm_leads", "crm_projects", "crm_quotations", "crm_revenue_collections", "apn_users"]));
    expect(routeDataTables("quotations", "admin")).toContain("projects");
    expect(routeDataTables("performance", "admin")).toEqual(expect.arrayContaining(["attendance", "leads", "transactions", "rewards"]));
    expect(routeDataTables("rewards", "admin")).toEqual(expect.arrayContaining(["rewards", "attendance", "leads", "projects"]));
    expect(routeDataTables("team", "admin")).toContain("apn_users");
    expect(routeDataTables("announcements", "admin")).toContain("audit");
    expect(routeDataTables("settings", "superadmin")).toEqual(expect.arrayContaining(["transactions", "withdrawals", "tasks", "projects", "students", "marketing", "leave", "updates"]));
    expect(apnTabs.partner).toHaveLength(18);
    expect(apnTabs.admin).toHaveLength(14);
    expect(routeDataTables("dashboard", "partner", "learn")).toContain("apn_training");
    expect(routeDataTables("dashboard", "partner", "learn")).not.toContain("apn_commission_projects");
    expect(routeDataTables("dashboard", "partner", "network")).toContain("apn_referral_relationships");
    expect(routeDataTables("dashboard", "partner", "wallet")).toContain("apn_leads");
    expect(routeDataTables("dashboard", "partner", "wallet")).toContain("apn_consolidated_wallets");
    expect(routeDataTables("dashboard", "partner", "profile")).toEqual(expect.arrayContaining(["apn_leads", "apn_commission_projects", "apn_revenue_collections", "apn_consolidated_wallets"]));
    expect(routeDataTables("apn", "admin", "partners")).toEqual(expect.arrayContaining(["apn_users", "apn_quotations", "apn_commission_projects", "apn_revenue_collections", "apn_notifications", "audit"]));
    expect(routeDataTables("apn", "admin", "hub")).toContain("apn_zone_requests");
    expect(routeDataTables("apn", "admin", "leads")).toContain("apn_commissions");
    expect(routeDataTables("apn", "admin", "commissions")).toContain("apn_consolidated_wallets");
    expect(routeDataTables("apn", "admin", "docs")).toContain("apn_documents");
    expect(routeDataTables("apn", "admin", "docs")).not.toContain("crm_leads");
    expect(routeDataTables("apn", "admin", "commissions")).toEqual(expect.arrayContaining(["transactions", "apn_leads", "apn_commission_projects", "apn_revenue_collections", "apn_consolidated_wallets"]));
    expect(routeDataTables("apn", "admin", "withdrawals")).toContain("apn_withdrawal_requests");
    expect(routeDataTables("apn", "admin", "withdrawals")).not.toContain("crm_leads");
    expect(routeDataTables("apn", "admin", "referrals")).toContain("apn_referral_relationships");
    expect(routeDataTables("apn", "admin", "referrals")).not.toContain("crm_leads");
    expect(routeDataTables("dashboard", "partner", "achievements")).toEqual(expect.arrayContaining(["apn_leads", "apn_commissions", "apn_commission_projects", "apn_revenue_collections"]));
    expect(routeDataTables("dashboard", "partner", "leaderboard")).toEqual(expect.arrayContaining(["apn_leads", "apn_commissions", "apn_commission_projects", "apn_revenue_collections"]));
    expect(routeDataTables("dashboard", "partner", "district")).toEqual(expect.arrayContaining(["apn_leads", "apn_commissions", "apn_commission_projects", "apn_revenue_collections"]));
    expect(routeDataTables("dashboard", "partner", "agreements")).toContain("apn_agreement_company");
    expect(routeDataTables("apn", "admin", "board")).toEqual(expect.arrayContaining(["apn_quotations", "apn_commission_projects", "apn_revenue_collections", "apn_warnings"]));
    expect(routeDataTables("concepts", "superadmin")).toContain("tasks");
    expect(routeDataTables("knowledge", "admin")).toEqual(expect.arrayContaining(["knowledge", "tasks", "notifications"]));
    expect(routeDataTables("quotations", "admin")).toContain("clients");
    expect(routeDataTables("invoices", "accountant")).toContain("clients");
    expect(routeDataTables("testing", "admin")).toContain("projects");
    expect(routeDataTables("clients", "admin")).toContain("quotations");
    expect(routeDataTables("dashboard", "staff")).toContain("resignations");
  });
});
