-- Shared chat interaction policy: authenticated reactions + sender-only 1h tombstone deletion.
create table if not exists public.team_chat_reactions(message_id text not null references public.team_chat(id) on delete cascade,reactor_id text not null,emoji text not null,created_at timestamptz not null default now(),primary key(message_id,reactor_id,emoji));
alter table public.team_chat_reactions enable row level security; revoke all on public.team_chat_reactions from public,anon,authenticated;
create or replace function public.chat_toggle_reaction(p_id text,p_emoji text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_uid text:=auth.uid()::text;v_emoji text:=trim(p_emoji);v_on boolean;begin if v_uid is null then raise exception 'Authentication required';end if;if v_emoji not in ('👍','❤️','😂','😮','😢','🎉') then raise exception 'Unsupported reaction';end if;if not exists(select 1 from public.team_chat c where c.id=p_id) then raise exception 'Message not found';end if;if exists(select 1 from public.team_chat_reactions r where r.message_id=p_id and r.reactor_id=v_uid and r.emoji=v_emoji) then delete from public.team_chat_reactions where message_id=p_id and reactor_id=v_uid and emoji=v_emoji;v_on:=false;else insert into public.team_chat_reactions(message_id,reactor_id,emoji) values(p_id,v_uid,v_emoji);v_on:=true;end if;return jsonb_build_object('reacted',v_on);end $$;
create or replace function public.chat_list_reactions(p_ids text[]) returns table(message_id text,emoji text,reaction_count bigint,mine boolean) language sql stable security definer set search_path='' as $$ select r.message_id,r.emoji,count(*)::bigint,bool_or(r.reactor_id=auth.uid()::text) from public.team_chat_reactions r where r.message_id=any(p_ids) group by r.message_id,r.emoji $$;
create or replace function public.chat_delete_message(p_id text) returns public.team_chat language plpgsql security definer set search_path='' as $$ declare r public.team_chat%rowtype;begin select * into r from public.team_chat where id=p_id for update;if not found then raise exception 'Message not found.';end if;if r.data->>'userId'<>auth.uid()::text then raise exception 'You can only delete your own message.' using errcode='42501';end if;if r.created_at<now()-interval '1 hour' then raise exception 'Messages can only be deleted within 1 hour.';end if;update public.team_chat set data=jsonb_set(jsonb_set(jsonb_set(jsonb_set(data,'{deleted}','true'::jsonb),'{text}','""'::jsonb,true),'{deletedBy}',to_jsonb(auth.uid()::text),true),'{deletedAt}',to_jsonb(now()),true),updated_at=now() where id=p_id returning * into r;delete from public.team_chat_reactions where message_id=p_id;return r;end $$;
alter table public.apn_chat_messages add column if not exists deleted_at timestamptz,add column if not exists deleted_by text;
create or replace function public.apn_delete_message(p_message_id uuid) returns table(ok boolean) language plpgsql security definer set search_path='' as $$ begin update public.apn_chat_messages m set body='This message was deleted',deleted_at=now(),deleted_by=auth.uid()::text,updated_at=now() where m.id=p_message_id and m.sender_id=auth.uid()::text and m.created_at>now()-interval '1 hour' and m.deleted_at is null;if not found then raise exception 'Message can only be deleted by its sender within 1 hour.';end if;delete from public.apn_chat_reactions where message_id=p_message_id;return query select true;end $$;
create or replace function public.apn_toggle_reaction(p_message_id uuid,p_emoji text) returns table(reacted boolean,reaction_count bigint) language plpgsql security definer set search_path='' as $$ declare v_self text:=auth.uid()::text;v_emoji text:=trim(p_emoji);v_conv uuid;v_reacted boolean;begin if v_emoji not in ('👍','❤️','😂','😮','😢','🎉') then raise exception 'Unsupported reaction.';end if;select conversation_id into v_conv from public.apn_chat_messages where id=p_message_id and deleted_at is null;if v_conv is null or not exists(select 1 from public.apn_chat_participants p where p.conversation_id=v_conv and p.participant_id=v_self) then raise exception 'Not a participant.';end if;if exists(select 1 from public.apn_chat_reactions where message_id=p_message_id and reactor_id=v_self and emoji=v_emoji) then delete from public.apn_chat_reactions where message_id=p_message_id and reactor_id=v_self and emoji=v_emoji;v_reacted:=false;else insert into public.apn_chat_reactions(message_id,reactor_id,emoji) values(p_message_id,v_self,v_emoji);v_reacted:=true;end if;return query select v_reacted,(select count(*) from public.apn_chat_reactions where message_id=p_message_id and emoji=v_emoji);end $$;
revoke all on function public.chat_toggle_reaction(text,text),public.chat_list_reactions(text[]),public.chat_delete_message(text),public.apn_delete_message(uuid),public.apn_toggle_reaction(uuid,text) from public,anon;
grant execute on function public.chat_toggle_reaction(text,text),public.chat_list_reactions(text[]),public.chat_delete_message(text),public.apn_delete_message(uuid),public.apn_toggle_reaction(uuid,text) to authenticated;
